-- PostgreSQL catalog compatibility layer for Exasol.
--
-- This script creates two schemas, PG_CATALOG and INFORMATION_SCHEMA, and
-- populates them with Exasol-backed compatibility views for the core metadata
-- surfaces used by PostgreSQL clients. PostgreSQL-specific features that do
-- not have an Exasol equivalent are exposed as empty views with the expected
-- columns so clients receive empty result sets instead of object-not-found
-- errors.

CREATE SCHEMA IF NOT EXISTS PG_CATALOG;
CREATE SCHEMA IF NOT EXISTS INFORMATION_SCHEMA;

CREATE OR REPLACE FUNCTION PG_CATALOG.OBJ_DESCRIPTION(
    OBJ_OID DECIMAL(18,0),
    CATALOG_NAME VARCHAR(128)
)
RETURN VARCHAR(2000)
IS
BEGIN
    RETURN NULL;
END OBJ_DESCRIPTION;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_GET_USERBYID(
    USER_OID DECIMAL(18,0)
)
RETURN VARCHAR(128)
IS
BEGIN
    RETURN CASE
        WHEN USER_OID = 10 THEN 'SYS'
        ELSE 'UNKNOWN'
    END;
END PG_GET_USERBYID;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_GET_EXPR(
    EXPR_TEXT VARCHAR(2000),
    REL_OID DECIMAL(18,0)
)
RETURN VARCHAR(2000)
IS
BEGIN
    RETURN EXPR_TEXT;
END PG_GET_EXPR;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_GET_CONSTRAINTDEF(
    CONSTRAINT_OID DECIMAL(18,0)
)
RETURN VARCHAR(2000)
IS
BEGIN
    RETURN NULL;
END PG_GET_CONSTRAINTDEF;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_GET_INDEXDEF(
    INDEX_OID DECIMAL(18,0)
)
RETURN VARCHAR(2000000)
IS
BEGIN
    RETURN NULL;
END PG_GET_INDEXDEF;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_STAT_GET_BLOCKS_FETCHED(
    REL_OID DECIMAL(18,0)
)
RETURN DECIMAL(18,0)
IS
BEGIN
    RETURN 0;
END PG_STAT_GET_BLOCKS_FETCHED;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_STAT_GET_BLOCKS_HIT(
    REL_OID DECIMAL(18,0)
)
RETURN DECIMAL(18,0)
IS
BEGIN
    RETURN 0;
END PG_STAT_GET_BLOCKS_HIT;
/

CREATE OR REPLACE VIEW PG_CATALOG.PG_DATABASE AS
SELECT
    CAST(1 AS DECIMAL(18,0)) AS OID,
    'exasol' AS DATNAME,
    CAST(10 AS DECIMAL(18,0)) AS DATDBA,
    CAST(6 AS DECIMAL(9,0)) AS ENCODING,
    'c' AS DATLOCPROVIDER,
    FALSE AS DATISTEMPLATE,
    TRUE AS DATALLOWCONN,
    FALSE AS DATHASLOGINEVT,
    CAST(-1 AS DECIMAL(9,0)) AS DATCONNLIMIT,
    CAST(0 AS DECIMAL(18,0)) AS DATFROZENXID,
    CAST(0 AS DECIMAL(18,0)) AS DATMINMXID,
    CAST(1663 AS DECIMAL(18,0)) AS DATTABLESPACE,
    'C.UTF-8' AS DATCOLLATE,
    'C.UTF-8' AS DATCTYPE,
    CAST(NULL AS VARCHAR(2000)) AS DATLOCALE,
    CAST(NULL AS VARCHAR(2000)) AS DATICURULES,
    CAST(NULL AS VARCHAR(2000)) AS DATCOLLVERSION,
    CAST(NULL AS VARCHAR(2000)) AS DATACL;

CREATE OR REPLACE VIEW PG_CATALOG.PG_USER AS
SELECT
    USER_NAME AS USENAME,
    CASE WHEN USER_NAME = 'SYS' THEN CAST(10 AS DECIMAL(18,0))
         ELSE CAST(10000 + ROW_NUMBER() OVER (ORDER BY USER_NAME) AS DECIMAL(18,0))
    END AS USESYSID,
    TRUE AS USECREATEDB,
    CASE WHEN USER_NAME = 'SYS' THEN TRUE ELSE FALSE END AS USESUPER,
    FALSE AS USEREPL,
    CASE WHEN USER_NAME = 'SYS' THEN TRUE ELSE FALSE END AS USEBYPASSRLS,
    CAST(NULL AS VARCHAR(64)) AS PASSWD,
    PASSWORD_EXPIRY AS VALUNTIL,
    CAST(NULL AS VARCHAR(2000)) AS USECONFIG
FROM SYS.EXA_DBA_USERS;

CREATE OR REPLACE VIEW PG_CATALOG.PG_GROUP AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS GRONAME,
    CAST(NULL AS DECIMAL(18,0)) AS GROSYSID,
    CAST(NULL AS VARCHAR(2000)) AS GROLIST
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_ROLES AS
WITH ROLE_BASE AS (
    SELECT
        USER_NAME AS ROLE_NAME,
        TRUE AS CAN_LOGIN,
        CASE WHEN USER_NAME = 'SYS' THEN CAST(10 AS DECIMAL(18,0))
             ELSE CAST(10000 + ROW_NUMBER() OVER (ORDER BY USER_NAME) AS DECIMAL(18,0))
        END AS ROLE_OID,
        USER_COMMENT AS ROLE_COMMENT
    FROM SYS.EXA_DBA_USERS
    UNION ALL
    SELECT
        ROLE_NAME,
        FALSE AS CAN_LOGIN,
        CAST(20000 + ROW_NUMBER() OVER (ORDER BY ROLE_NAME) AS DECIMAL(18,0)) AS ROLE_OID,
        ROLE_COMMENT
    FROM SYS.EXA_DBA_ROLES
)
SELECT
    ROLE_OID AS OID,
    ROLE_NAME AS ROLNAME,
    CASE WHEN ROLE_NAME = 'SYS' THEN TRUE ELSE FALSE END AS ROLSUPER,
    TRUE AS ROLINHERIT,
    CASE WHEN ROLE_NAME = 'SYS' THEN TRUE ELSE FALSE END AS ROLCREATEROLE,
    CASE WHEN ROLE_NAME = 'SYS' THEN TRUE ELSE FALSE END AS ROLCREATEDB,
    CAN_LOGIN AS ROLCANLOGIN,
    FALSE AS ROLREPLICATION,
    CAST(-1 AS DECIMAL(9,0)) AS ROLCONNLIMIT,
    CAST(NULL AS VARCHAR(64)) AS ROLPASSWORD,
    CAST(NULL AS TIMESTAMP) AS ROLVALIDUNTIL,
    CASE WHEN ROLE_NAME = 'SYS' THEN TRUE ELSE FALSE END AS ROLBYPASSRLS,
    CAST(NULL AS VARCHAR(2000)) AS ROLCONFIG,
    ROLE_COMMENT AS ROLCOMMENT
FROM ROLE_BASE;

CREATE OR REPLACE VIEW PG_CATALOG.PG_AUTHID AS
SELECT
    OID,
    ROLNAME,
    ROLSUPER,
    ROLINHERIT,
    ROLCREATEROLE,
    ROLCREATEDB,
    ROLCANLOGIN,
    ROLREPLICATION,
    ROLBYPASSRLS,
    ROLCONNLIMIT,
    ROLPASSWORD,
    ROLVALIDUNTIL
FROM PG_CATALOG.PG_ROLES;

CREATE OR REPLACE VIEW PG_CATALOG.PG_AUTH_MEMBERS AS
WITH ROLE_LOOKUP AS (
    SELECT OID, ROLNAME
    FROM PG_CATALOG.PG_ROLES
)
SELECT
    CAST(900000 + ROW_NUMBER() OVER (ORDER BY RP.GRANTED_ROLE, RP.GRANTEE) AS DECIMAL(18,0)) AS OID,
    COALESCE(ROLE_OID.OID, CAST(0 AS DECIMAL(18,0))) AS ROLEID,
    COALESCE(MEMBER_OID.OID, CAST(0 AS DECIMAL(18,0))) AS MEMBER,
    CAST(10 AS DECIMAL(18,0)) AS GRANTOR,
    COALESCE(RP.ADMIN_OPTION, FALSE) AS ADMIN_OPTION,
    TRUE AS INHERIT_OPTION,
    TRUE AS SET_OPTION
FROM SYS.EXA_DBA_ROLE_PRIVS RP
LEFT JOIN ROLE_LOOKUP ROLE_OID
  ON ROLE_OID.ROLNAME = RP.GRANTED_ROLE
LEFT JOIN ROLE_LOOKUP MEMBER_OID
  ON MEMBER_OID.ROLNAME = RP.GRANTEE;

CREATE OR REPLACE VIEW PG_CATALOG.PG_SETTINGS AS
SELECT
    'server_version' AS "NAME",
    '16.6-exasol-gateway' AS "SETTING",
    CAST(NULL AS VARCHAR(64)) AS "UNIT",
    'internal' AS "CONTEXT",
    'string' AS "VARTYPE",
    'default' AS "SOURCE",
    CAST(NULL AS VARCHAR(128)) AS "MIN_VAL",
    CAST(NULL AS VARCHAR(128)) AS "MAX_VAL",
    CAST(NULL AS VARCHAR(2000)) AS "ENUMVALS",
    '16.6-exasol-gateway' AS "BOOT_VAL",
    '16.6-exasol-gateway' AS "RESET_VAL",
    CAST(NULL AS VARCHAR(2000)) AS "SOURCEFILE",
    CAST(NULL AS DECIMAL(18,0)) AS "SOURCELINE",
    FALSE AS "PENDING_RESTART"
UNION ALL
SELECT
    'client_encoding',
    'UTF8',
    CAST(NULL AS VARCHAR(64)),
    'user',
    'string',
    'client',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    'UTF8',
    'UTF8',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE
UNION ALL
SELECT
    'standard_conforming_strings',
    'on',
    CAST(NULL AS VARCHAR(64)),
    'user',
    'bool',
    'default',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    'on',
    'on',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE
UNION ALL
SELECT
    'TimeZone',
    'Etc/UTC',
    CAST(NULL AS VARCHAR(64)),
    'user',
    'string',
    'default',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    'Etc/UTC',
    'Etc/UTC',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE
UNION ALL
SELECT
    'max_index_keys',
    '32',
    CAST(NULL AS VARCHAR(64)),
    'internal',
    'integer',
    'default',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    '32',
    '32',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE
UNION ALL
SELECT
    'server_encoding',
    'UTF8',
    CAST(NULL AS VARCHAR(64)),
    'internal',
    'string',
    'default',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    'UTF8',
    'UTF8',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE
UNION ALL
SELECT
    'server_version_num',
    '160006',
    CAST(NULL AS VARCHAR(64)),
    'internal',
    'integer',
    'default',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    '160006',
    '160006',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE
UNION ALL
SELECT
    'integer_datetimes',
    'on',
    CAST(NULL AS VARCHAR(64)),
    'internal',
    'bool',
    'default',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    'on',
    'on',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE
UNION ALL
SELECT
    'search_path',
    '"$user", public',
    CAST(NULL AS VARCHAR(64)),
    'user',
    'string',
    'session',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    '"$user", public',
    '"$user", public',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE;

CREATE OR REPLACE VIEW PG_CATALOG.PG_NAMESPACE AS
WITH ROLE_LOOKUP AS (
    SELECT OID, ROLNAME
    FROM PG_CATALOG.PG_ROLES
)
SELECT
    SCHEMA_OBJECT_ID AS OID,
    SCHEMA_NAME AS NSPNAME,
    COALESCE(R.OID, CAST(10 AS DECIMAL(18,0))) AS NSPOWNER,
    CAST(NULL AS VARCHAR(2000)) AS NSPACL
FROM SYS.EXA_DBA_SCHEMAS
LEFT JOIN ROLE_LOOKUP R
  ON R.ROLNAME = SCHEMA_OWNER
WHERE SCHEMA_NAME NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA')
UNION ALL
SELECT CAST(11 AS DECIMAL(18,0)), 'PG_CATALOG', CAST(10 AS DECIMAL(18,0)), CAST(NULL AS VARCHAR(2000))
UNION ALL
SELECT CAST(12 AS DECIMAL(18,0)), 'INFORMATION_SCHEMA', CAST(10 AS DECIMAL(18,0)), CAST(NULL AS VARCHAR(2000));

CREATE OR REPLACE VIEW PG_CATALOG.PG_TABLESPACE AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS OID,
    CAST(NULL AS VARCHAR(128)) AS SPCNAME,
    CAST(NULL AS DECIMAL(18,0)) AS SPCOWNER,
    CAST(NULL AS VARCHAR(2000)) AS SPCACL,
    CAST(NULL AS VARCHAR(2000)) AS SPCOPTIONS
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_AM AS
SELECT
    CAST(403 AS DECIMAL(18,0)) AS OID,
    'btree' AS AMNAME,
    CAST(0 AS DECIMAL(18,0)) AS AMHANDLER,
    'i' AS AMTYPE;

CREATE OR REPLACE VIEW PG_CATALOG.PG_TYPE AS
SELECT CAST(16 AS DECIMAL(18,0)) AS OID, 'bool' AS TYPNAME, CAST(11 AS DECIMAL(18,0)) AS TYPNAMESPACE, CAST(10 AS DECIMAL(18,0)) AS TYPOWNER, CAST(1 AS DECIMAL(9,0)) AS TYPLEN, FALSE AS TYPBYVAL, 'b' AS TYPTYPE, FALSE AS TYPNOTNULL, CAST(-1 AS DECIMAL(18,0)) AS TYPTYPMOD, CAST(0 AS DECIMAL(18,0)) AS TYPBASETYPE
UNION ALL
SELECT CAST(18 AS DECIMAL(18,0)), 'char', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(1 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(19 AS DECIMAL(18,0)), 'name', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(64 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(20 AS DECIMAL(18,0)), 'int8', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(8 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(21 AS DECIMAL(18,0)), 'int2', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(2 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(22 AS DECIMAL(18,0)), 'int2vector', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(23 AS DECIMAL(18,0)), 'int4', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(4 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(25 AS DECIMAL(18,0)), 'text', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(26 AS DECIMAL(18,0)), 'oid', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(4 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(30 AS DECIMAL(18,0)), 'oidvector', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1042 AS DECIMAL(18,0)), 'bpchar', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1043 AS DECIMAL(18,0)), 'varchar', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1082 AS DECIMAL(18,0)), 'date', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(4 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1114 AS DECIMAL(18,0)), 'timestamp', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(8 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1184 AS DECIMAL(18,0)), 'timestamptz', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(8 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(700 AS DECIMAL(18,0)), 'float4', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(4 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(701 AS DECIMAL(18,0)), 'float8', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(8 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1700 AS DECIMAL(18,0)), 'numeric', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(2249 AS DECIMAL(18,0)), 'record', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'p', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0));

CREATE OR REPLACE VIEW PG_CATALOG.PG_CLASS AS
WITH TABLE_COLUMNS AS (
    SELECT COLUMN_SCHEMA, COLUMN_TABLE, COUNT(*) AS COLUMN_COUNT
    FROM SYS.EXA_DBA_COLUMNS
    WHERE COLUMN_OBJECT_TYPE = 'TABLE'
    GROUP BY COLUMN_SCHEMA, COLUMN_TABLE
),
VIEW_COLUMNS AS (
    SELECT COLUMN_SCHEMA, COLUMN_TABLE, COUNT(*) AS COLUMN_COUNT
    FROM SYS.EXA_DBA_COLUMNS
    WHERE COLUMN_OBJECT_TYPE = 'VIEW'
    GROUP BY COLUMN_SCHEMA, COLUMN_TABLE
),
TABLE_INDEXES AS (
    SELECT INDEX_SCHEMA, INDEX_TABLE, COUNT(*) AS INDEX_COUNT
    FROM SYS.EXA_DBA_INDICES
    GROUP BY INDEX_SCHEMA, INDEX_TABLE
),
ROLE_LOOKUP AS (
    SELECT OID, ROLNAME
    FROM PG_CATALOG.PG_ROLES
)
SELECT
    T.TABLE_OBJECT_ID AS OID,
    T.TABLE_NAME AS RELNAME,
    N.OID AS RELNAMESPACE,
    CAST(0 AS DECIMAL(18,0)) AS RELTYPE,
    CAST(0 AS DECIMAL(18,0)) AS RELOFTYPE,
    COALESCE(R.OID, CAST(10 AS DECIMAL(18,0))) AS RELOWNER,
    CAST(0 AS DECIMAL(18,0)) AS RELAM,
    CAST(0 AS DECIMAL(18,0)) AS RELFILENODE,
    CAST(0 AS DECIMAL(18,0)) AS RELTABLESPACE,
    CAST(0 AS DECIMAL(18,0)) AS RELPAGES,
    COALESCE(T.TABLE_ROW_COUNT, 0) AS RELTUPLES,
    CAST(0 AS DECIMAL(18,0)) AS RELALLVISIBLE,
    CAST(0 AS DECIMAL(18,0)) AS RELTOASTRELID,
    COALESCE(I.INDEX_COUNT, 0) > 0 AS RELHASINDEX,
    FALSE AS RELISSHARED,
    'p' AS RELPERSISTENCE,
    'r' AS RELKIND,
    COALESCE(C.COLUMN_COUNT, 0) AS RELNATTS,
    CAST(0 AS DECIMAL(18,0)) AS RELCHECKS,
    FALSE AS RELHASRULES,
    FALSE AS RELHASTRIGGERS,
    FALSE AS RELHASSUBCLASS,
    FALSE AS RELROWSECURITY,
    FALSE AS RELFORCEROWSECURITY,
    TRUE AS RELISPOPULATED,
    'n' AS RELREPLIDENT,
    FALSE AS RELISPARTITION,
    CAST(0 AS DECIMAL(18,0)) AS RELREWRITE,
    CAST(0 AS DECIMAL(18,0)) AS RELFROZENXID,
    CAST(0 AS DECIMAL(18,0)) AS RELMINMXID,
    CAST(NULL AS VARCHAR(2000)) AS RELACL,
    CAST(NULL AS VARCHAR(2000)) AS RELOPTIONS,
    CAST(NULL AS VARCHAR(2000)) AS RELPARTBOUND
FROM SYS.EXA_DBA_TABLES T
JOIN PG_CATALOG.PG_NAMESPACE N
  ON N.NSPNAME = T.TABLE_SCHEMA
LEFT JOIN ROLE_LOOKUP R
  ON R.ROLNAME = T.TABLE_OWNER
LEFT JOIN TABLE_COLUMNS C
  ON C.COLUMN_SCHEMA = T.TABLE_SCHEMA AND C.COLUMN_TABLE = T.TABLE_NAME
LEFT JOIN TABLE_INDEXES I
  ON I.INDEX_SCHEMA = T.TABLE_SCHEMA AND I.INDEX_TABLE = T.TABLE_NAME
WHERE T.TABLE_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA')
UNION ALL
SELECT
    V.VIEW_OBJECT_ID AS OID,
    V.VIEW_NAME AS RELNAME,
    N.OID AS RELNAMESPACE,
    CAST(0 AS DECIMAL(18,0)) AS RELTYPE,
    CAST(0 AS DECIMAL(18,0)) AS RELOFTYPE,
    COALESCE(R.OID, CAST(10 AS DECIMAL(18,0))) AS RELOWNER,
    CAST(0 AS DECIMAL(18,0)) AS RELAM,
    CAST(0 AS DECIMAL(18,0)) AS RELFILENODE,
    CAST(0 AS DECIMAL(18,0)) AS RELTABLESPACE,
    CAST(0 AS DECIMAL(18,0)) AS RELPAGES,
    CAST(0 AS DECIMAL(18,0)) AS RELTUPLES,
    CAST(0 AS DECIMAL(18,0)) AS RELALLVISIBLE,
    CAST(0 AS DECIMAL(18,0)) AS RELTOASTRELID,
    FALSE AS RELHASINDEX,
    FALSE AS RELISSHARED,
    'p' AS RELPERSISTENCE,
    'v' AS RELKIND,
    COALESCE(C.COLUMN_COUNT, 0) AS RELNATTS,
    CAST(0 AS DECIMAL(18,0)) AS RELCHECKS,
    FALSE AS RELHASRULES,
    FALSE AS RELHASTRIGGERS,
    FALSE AS RELHASSUBCLASS,
    FALSE AS RELROWSECURITY,
    FALSE AS RELFORCEROWSECURITY,
    TRUE AS RELISPOPULATED,
    'n' AS RELREPLIDENT,
    FALSE AS RELISPARTITION,
    CAST(0 AS DECIMAL(18,0)) AS RELREWRITE,
    CAST(0 AS DECIMAL(18,0)) AS RELFROZENXID,
    CAST(0 AS DECIMAL(18,0)) AS RELMINMXID,
    CAST(NULL AS VARCHAR(2000)) AS RELACL,
    CAST(NULL AS VARCHAR(2000)) AS RELOPTIONS,
    CAST(NULL AS VARCHAR(2000)) AS RELPARTBOUND
FROM SYS.EXA_DBA_VIEWS V
JOIN PG_CATALOG.PG_NAMESPACE N
  ON N.NSPNAME = V.VIEW_SCHEMA
LEFT JOIN ROLE_LOOKUP R
  ON R.ROLNAME = V.VIEW_OWNER
LEFT JOIN VIEW_COLUMNS C
  ON C.COLUMN_SCHEMA = V.VIEW_SCHEMA AND C.COLUMN_TABLE = V.VIEW_NAME
WHERE V.VIEW_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA')
UNION ALL
SELECT
    I.INDEX_OBJECT_ID AS OID,
    I.INDEX_TABLE || '_IDX_' || CAST(I.INDEX_OBJECT_ID AS VARCHAR(20)) AS RELNAME,
    N.OID AS RELNAMESPACE,
    CAST(0 AS DECIMAL(18,0)) AS RELTYPE,
    CAST(0 AS DECIMAL(18,0)) AS RELOFTYPE,
    COALESCE(R.OID, CAST(10 AS DECIMAL(18,0))) AS RELOWNER,
    CAST(403 AS DECIMAL(18,0)) AS RELAM,
    CAST(0 AS DECIMAL(18,0)) AS RELFILENODE,
    CAST(0 AS DECIMAL(18,0)) AS RELTABLESPACE,
    CAST(0 AS DECIMAL(18,0)) AS RELPAGES,
    CAST(0 AS DECIMAL(18,0)) AS RELTUPLES,
    CAST(0 AS DECIMAL(18,0)) AS RELALLVISIBLE,
    CAST(0 AS DECIMAL(18,0)) AS RELTOASTRELID,
    FALSE AS RELHASINDEX,
    FALSE AS RELISSHARED,
    'p' AS RELPERSISTENCE,
    'i' AS RELKIND,
    CAST(0 AS DECIMAL(18,0)) AS RELNATTS,
    CAST(0 AS DECIMAL(18,0)) AS RELCHECKS,
    FALSE AS RELHASRULES,
    FALSE AS RELHASTRIGGERS,
    FALSE AS RELHASSUBCLASS,
    FALSE AS RELROWSECURITY,
    FALSE AS RELFORCEROWSECURITY,
    TRUE AS RELISPOPULATED,
    'n' AS RELREPLIDENT,
    FALSE AS RELISPARTITION,
    CAST(0 AS DECIMAL(18,0)) AS RELREWRITE,
    CAST(0 AS DECIMAL(18,0)) AS RELFROZENXID,
    CAST(0 AS DECIMAL(18,0)) AS RELMINMXID,
    CAST(NULL AS VARCHAR(2000)) AS RELACL,
    CAST(NULL AS VARCHAR(2000)) AS RELOPTIONS,
    CAST(NULL AS VARCHAR(2000)) AS RELPARTBOUND
FROM SYS.EXA_DBA_INDICES I
JOIN PG_CATALOG.PG_NAMESPACE N
  ON N.NSPNAME = I.INDEX_SCHEMA
LEFT JOIN ROLE_LOOKUP R
  ON R.ROLNAME = I.INDEX_OWNER
WHERE I.INDEX_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW PG_CATALOG.PG_ATTRIBUTE AS
SELECT
    CLS.OID AS ATTRELID,
    COL.COLUMN_NAME AS ATTNAME,
    CASE
        WHEN COL.COLUMN_TYPE LIKE 'DECIMAL(%' THEN CAST(1700 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE LIKE 'VARCHAR(%' THEN CAST(1043 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE LIKE 'CHAR(%' THEN CAST(1042 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE LIKE 'TIMESTAMP%' THEN CAST(1114 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE = 'DATE' THEN CAST(1082 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE = 'BOOLEAN' THEN CAST(16 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE IN ('DOUBLE', 'DOUBLE PRECISION') THEN CAST(701 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE = 'REAL' THEN CAST(700 AS DECIMAL(18,0))
        ELSE CAST(25 AS DECIMAL(18,0))
    END AS ATTTYPID,
    CASE
        WHEN COL.COLUMN_TYPE LIKE 'TIMESTAMP%' THEN CAST(8 AS DECIMAL(9,0))
        WHEN COL.COLUMN_TYPE = 'DATE' THEN CAST(4 AS DECIMAL(9,0))
        WHEN COL.COLUMN_TYPE = 'BOOLEAN' THEN CAST(1 AS DECIMAL(9,0))
        WHEN COL.COLUMN_TYPE = 'REAL' THEN CAST(4 AS DECIMAL(9,0))
        WHEN COL.COLUMN_TYPE IN ('DOUBLE', 'DOUBLE PRECISION') THEN CAST(8 AS DECIMAL(9,0))
        ELSE CAST(-1 AS DECIMAL(9,0))
    END AS ATTLEN,
    COL.COLUMN_ORDINAL_POSITION AS ATTNUM,
    CASE
        WHEN COL.COLUMN_TYPE LIKE 'DECIMAL(%' THEN (COALESCE(COL.COLUMN_NUM_PREC, 36) * 65536) + COALESCE(COL.COLUMN_NUM_SCALE, 0) + 4
        WHEN COL.COLUMN_TYPE LIKE 'VARCHAR(%' THEN COALESCE(COL.COLUMN_MAXSIZE, 0) + 4
        WHEN COL.COLUMN_TYPE LIKE 'CHAR(%' THEN COALESCE(COL.COLUMN_MAXSIZE, 0) + 4
        WHEN COL.COLUMN_TYPE LIKE 'TIMESTAMP%' THEN 10
        ELSE -1
    END AS ATTTYPMOD,
    CAST(0 AS DECIMAL(9,0)) AS ATTNDIMS,
    FALSE AS ATTBYVAL,
    COALESCE(COL.COLUMN_IS_NULLABLE = FALSE, FALSE) AS ATTNOTNULL,
    CAST(NULL AS VARCHAR(1)) AS ATTIDENTITY,
    CAST(NULL AS VARCHAR(1)) AS ATTGENERATED,
    FALSE AS ATTISDROPPED
FROM SYS.EXA_DBA_COLUMNS COL
JOIN PG_CATALOG.PG_NAMESPACE NS
  ON NS.NSPNAME = COL.COLUMN_SCHEMA
JOIN PG_CATALOG.PG_CLASS CLS
  ON CLS.RELNAME = COL.COLUMN_TABLE
 AND CLS.RELNAMESPACE = NS.OID
WHERE COL.COLUMN_OBJECT_TYPE IN ('TABLE', 'VIEW');

CREATE OR REPLACE VIEW PG_CATALOG.PG_ATTRDEF AS
SELECT
    CAST((CLS.OID * 1000) + COL.COLUMN_ORDINAL_POSITION AS DECIMAL(18,0)) AS OID,
    CLS.OID AS ADRELID,
    COL.COLUMN_ORDINAL_POSITION AS ADNUM,
    COL.COLUMN_DEFAULT AS ADBIN
FROM SYS.EXA_DBA_COLUMNS COL
JOIN PG_CATALOG.PG_NAMESPACE NS
  ON NS.NSPNAME = COL.COLUMN_SCHEMA
JOIN PG_CATALOG.PG_CLASS CLS
  ON CLS.RELNAME = COL.COLUMN_TABLE
 AND CLS.RELNAMESPACE = NS.OID
WHERE COL.COLUMN_DEFAULT IS NOT NULL
  AND COL.COLUMN_OBJECT_TYPE IN ('TABLE', 'VIEW');

CREATE OR REPLACE VIEW PG_CATALOG.PG_DESCRIPTION AS
SELECT
    NS.OID AS OBJOID,
    CAST(2615 AS DECIMAL(18,0)) AS CLASSOID,
    CAST(0 AS DECIMAL(18,0)) AS OBJSUBID,
    S.SCHEMA_COMMENT AS DESCRIPTION
FROM SYS.EXA_DBA_SCHEMAS S
JOIN PG_CATALOG.PG_NAMESPACE NS
  ON NS.NSPNAME = S.SCHEMA_NAME
WHERE S.SCHEMA_COMMENT IS NOT NULL
UNION ALL
SELECT
    CLS.OID AS OBJOID,
    CAST(1259 AS DECIMAL(18,0)) AS CLASSOID,
    CAST(0 AS DECIMAL(18,0)) AS OBJSUBID,
    OBJ.OBJECT_COMMENT AS DESCRIPTION
FROM SYS.EXA_DBA_OBJECTS OBJ
JOIN PG_CATALOG.PG_CLASS CLS
  ON CLS.OID = OBJ.OBJECT_ID
WHERE OBJ.OBJECT_COMMENT IS NOT NULL
UNION ALL
SELECT
    CLS.OID AS OBJOID,
    CAST(1259 AS DECIMAL(18,0)) AS CLASSOID,
    COL.COLUMN_ORDINAL_POSITION AS OBJSUBID,
    COL.COLUMN_COMMENT AS DESCRIPTION
FROM SYS.EXA_DBA_COLUMNS COL
JOIN PG_CATALOG.PG_NAMESPACE NS
  ON NS.NSPNAME = COL.COLUMN_SCHEMA
JOIN PG_CATALOG.PG_CLASS CLS
  ON CLS.RELNAME = COL.COLUMN_TABLE
 AND CLS.RELNAMESPACE = NS.OID
WHERE COL.COLUMN_COMMENT IS NOT NULL
  AND COL.COLUMN_OBJECT_TYPE IN ('TABLE', 'VIEW')
UNION ALL
SELECT
    I.INDEX_OBJECT_ID AS OBJOID,
    CAST(1259 AS DECIMAL(18,0)) AS CLASSOID,
    CAST(0 AS DECIMAL(18,0)) AS OBJSUBID,
    I.REMARKS AS DESCRIPTION
FROM SYS.EXA_DBA_INDICES I
WHERE I.REMARKS IS NOT NULL
UNION ALL
SELECT
    F.FUNCTION_OBJECT_ID AS OBJOID,
    CAST(1255 AS DECIMAL(18,0)) AS CLASSOID,
    CAST(0 AS DECIMAL(18,0)) AS OBJSUBID,
    F.FUNCTION_COMMENT AS DESCRIPTION
FROM SYS.EXA_DBA_FUNCTIONS F
WHERE F.FUNCTION_COMMENT IS NOT NULL;

CREATE OR REPLACE VIEW PG_CATALOG.PG_INDEX AS
WITH TABLE_LOOKUP AS (
    SELECT
        OID,
        RELNAMESPACE,
        RELNAME
    FROM PG_CATALOG.PG_CLASS
    WHERE RELKIND = 'r'
)
SELECT
    I.INDEX_OBJECT_ID AS INDEXRELID,
    T.OID AS INDRELID,
    CAST(0 AS DECIMAL(9,0)) AS INDNATTS,
    CAST(0 AS DECIMAL(9,0)) AS INDNKEYATTS,
    FALSE AS INDISUNIQUE,
    FALSE AS INDNULLSNOTDISTINCT,
    FALSE AS INDISPRIMARY,
    FALSE AS INDISEXCLUSION,
    TRUE AS INDISIMMEDIATE,
    FALSE AS INDISCLUSTERED,
    TRUE AS INDISVALID,
    FALSE AS INDCHECKXMIN,
    TRUE AS INDISREADY,
    TRUE AS INDISLIVE,
    FALSE AS INISREPLICAIDENT,
    CAST(NULL AS VARCHAR(2000)) AS INDKEY,
    CAST(NULL AS VARCHAR(2000)) AS INDCOLLATION,
    CAST(NULL AS VARCHAR(2000)) AS INDCLASS,
    CAST(NULL AS VARCHAR(2000)) AS INDOPTION,
    CAST(NULL AS VARCHAR(2000000)) AS INDEXPRS,
    CAST(NULL AS VARCHAR(2000000)) AS INDPRED
FROM SYS.EXA_DBA_INDICES I
JOIN PG_CATALOG.PG_NAMESPACE N
  ON N.NSPNAME = I.INDEX_SCHEMA
JOIN TABLE_LOOKUP T
  ON T.RELNAMESPACE = N.OID
 AND T.RELNAME = I.INDEX_TABLE;

CREATE OR REPLACE VIEW PG_CATALOG.PG_CONSTRAINT AS
WITH REF_TARGET AS (
    SELECT
        CONSTRAINT_SCHEMA,
        CONSTRAINT_TABLE,
        CONSTRAINT_NAME,
        MAX(REFERENCED_SCHEMA) AS REFERENCED_SCHEMA,
        MAX(REFERENCED_TABLE) AS REFERENCED_TABLE
    FROM SYS.EXA_DBA_CONSTRAINT_COLUMNS
    GROUP BY CONSTRAINT_SCHEMA, CONSTRAINT_TABLE, CONSTRAINT_NAME
),
CON_KEYS AS (
    SELECT
        CONSTRAINT_SCHEMA,
        CONSTRAINT_TABLE,
        CONSTRAINT_NAME,
        '{' || GROUP_CONCAT(CAST(ORDINAL_POSITION AS VARCHAR(12)) ORDER BY ORDINAL_POSITION SEPARATOR ',') || '}' AS CONKEY
    FROM SYS.EXA_DBA_CONSTRAINT_COLUMNS
    GROUP BY CONSTRAINT_SCHEMA, CONSTRAINT_TABLE, CONSTRAINT_NAME
),
REF_KEYS AS (
    SELECT
        C.CONSTRAINT_SCHEMA,
        C.CONSTRAINT_TABLE,
        C.CONSTRAINT_NAME,
        '{' || GROUP_CONCAT(CAST(RC.COLUMN_ORDINAL_POSITION AS VARCHAR(12)) ORDER BY C.ORDINAL_POSITION SEPARATOR ',') || '}' AS CONFKEY
    FROM SYS.EXA_DBA_CONSTRAINT_COLUMNS C
    JOIN SYS.EXA_DBA_COLUMNS RC
      ON RC.COLUMN_SCHEMA = C.REFERENCED_SCHEMA
     AND RC.COLUMN_TABLE = C.REFERENCED_TABLE
     AND RC.COLUMN_NAME = C.REFERENCED_COLUMN
     AND RC.COLUMN_OBJECT_TYPE = 'TABLE'
    WHERE C.CONSTRAINT_TYPE = 'FOREIGN KEY'
    GROUP BY C.CONSTRAINT_SCHEMA, C.CONSTRAINT_TABLE, C.CONSTRAINT_NAME
)
SELECT
    CAST(500000 + ROW_NUMBER() OVER (ORDER BY C.CONSTRAINT_SCHEMA, C.CONSTRAINT_TABLE, C.CONSTRAINT_NAME) AS DECIMAL(18,0)) AS OID,
    C.CONSTRAINT_NAME AS CONNAME,
    NS.OID AS CONNAMESPACE,
    CASE
        WHEN C.CONSTRAINT_TYPE = 'PRIMARY KEY' THEN 'p'
        WHEN C.CONSTRAINT_TYPE = 'FOREIGN KEY' THEN 'f'
        WHEN C.CONSTRAINT_TYPE = 'NOT NULL' THEN 'n'
        ELSE 'c'
    END AS CONTYPE,
    FALSE AS CONDEFERRABLE,
    FALSE AS CONDEFERRED,
    TRUE AS CONVALIDATED,
    CLS.OID AS CONRELID,
    CAST(0 AS DECIMAL(18,0)) AS CONTYPID,
    CAST(0 AS DECIMAL(18,0)) AS CONINDID,
    CAST(0 AS DECIMAL(18,0)) AS CONPARENTID,
    CAST(CASE WHEN C.CONSTRAINT_TYPE = 'FOREIGN KEY' THEN REFCLS.OID ELSE 0 END AS DECIMAL(18,0)) AS CONFRELID,
    CK.CONKEY AS CONKEY,
    RK.CONFKEY AS CONFKEY,
    'a' AS CONFUPDTYPE,
    'a' AS CONFDELTYPE,
    's' AS CONMATCHTYPE,
    TRUE AS CONISLOCAL,
    CAST(0 AS DECIMAL(9,0)) AS CONINHCOUNT,
    FALSE AS CONNOINHERIT,
    CAST(NULL AS VARCHAR(2000)) AS CONBIN
FROM SYS.EXA_DBA_CONSTRAINTS C
JOIN PG_CATALOG.PG_NAMESPACE NS
  ON NS.NSPNAME = C.CONSTRAINT_SCHEMA
JOIN PG_CATALOG.PG_CLASS CLS
  ON CLS.RELNAME = C.CONSTRAINT_TABLE
 AND CLS.RELNAMESPACE = NS.OID
LEFT JOIN REF_TARGET RT
  ON RT.CONSTRAINT_SCHEMA = C.CONSTRAINT_SCHEMA
 AND RT.CONSTRAINT_TABLE = C.CONSTRAINT_TABLE
 AND RT.CONSTRAINT_NAME = C.CONSTRAINT_NAME
LEFT JOIN PG_CATALOG.PG_NAMESPACE RNS
  ON RNS.NSPNAME = RT.REFERENCED_SCHEMA
LEFT JOIN PG_CATALOG.PG_CLASS REFCLS
  ON REFCLS.RELNAME = RT.REFERENCED_TABLE
 AND REFCLS.RELNAMESPACE = RNS.OID
LEFT JOIN CON_KEYS CK
  ON CK.CONSTRAINT_SCHEMA = C.CONSTRAINT_SCHEMA
 AND CK.CONSTRAINT_TABLE = C.CONSTRAINT_TABLE
 AND CK.CONSTRAINT_NAME = C.CONSTRAINT_NAME
LEFT JOIN REF_KEYS RK
  ON RK.CONSTRAINT_SCHEMA = C.CONSTRAINT_SCHEMA
 AND RK.CONSTRAINT_TABLE = C.CONSTRAINT_TABLE
 AND RK.CONSTRAINT_NAME = C.CONSTRAINT_NAME
WHERE C.CONSTRAINT_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW PG_CATALOG.PG_TABLES AS
SELECT
    TABLE_SCHEMA AS SCHEMANAME,
    TABLE_NAME AS TABLENAME,
    TABLE_OWNER AS TABLEOWNER,
    CAST(NULL AS VARCHAR(128)) AS TABLESPACE,
    FALSE AS HASINDEXES,
    FALSE AS HASRULES,
    FALSE AS HASTRIGGERS,
    FALSE AS ROWSECURITY
FROM SYS.EXA_DBA_TABLES
WHERE TABLE_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW PG_CATALOG.PG_VIEWS AS
SELECT
    VIEW_SCHEMA AS SCHEMANAME,
    VIEW_NAME AS VIEWNAME,
    VIEW_OWNER AS VIEWOWNER,
    VIEW_TEXT AS DEFINITION
FROM SYS.EXA_DBA_VIEWS
WHERE VIEW_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW PG_CATALOG.PG_MATVIEWS AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS SCHEMANAME,
    CAST(NULL AS VARCHAR(128)) AS MATVIEWNAME,
    CAST(NULL AS VARCHAR(128)) AS MATVIEWOWNER,
    CAST(NULL AS VARCHAR(128)) AS TABLESPACE,
    CAST(NULL AS BOOLEAN) AS HASINDEXES,
    CAST(NULL AS BOOLEAN) AS ISPOPULATED,
    CAST(NULL AS VARCHAR(2000000)) AS DEFINITION
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_LOCKS AS
SELECT
    CAST(NULL AS VARCHAR(32)) AS LOCKTYPE,
    CAST(NULL AS DECIMAL(18,0)) AS DATABASE,
    CAST(NULL AS DECIMAL(18,0)) AS RELATION,
    CAST(NULL AS DECIMAL(18,0)) AS PAGE,
    CAST(NULL AS DECIMAL(18,0)) AS TUPLE,
    CAST(NULL AS VARCHAR(64)) AS VIRTUALXID,
    CAST(NULL AS DECIMAL(18,0)) AS TRANSACTIONID,
    CAST(NULL AS DECIMAL(18,0)) AS CLASSID,
    CAST(NULL AS DECIMAL(18,0)) AS OBJID,
    CAST(NULL AS DECIMAL(18,0)) AS OBJSUBID,
    CAST(NULL AS VARCHAR(64)) AS VIRTUALTRANSACTION,
    CAST(NULL AS DECIMAL(18,0)) AS PID,
    CAST(NULL AS VARCHAR(64)) AS MODE,
    CAST(NULL AS BOOLEAN) AS "GRANTED",
    CAST(NULL AS BOOLEAN) AS FASTPATH,
    CAST(NULL AS TIMESTAMP) AS WAITSTART
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_STAT_ACTIVITY AS
SELECT
    CAST(1 AS DECIMAL(18,0)) AS DATID,
    'exasol' AS DATNAME,
    SESSION_ID AS PID,
    CAST(NULL AS DECIMAL(18,0)) AS LEADER_PID,
    CASE WHEN USER_NAME = 'SYS' THEN CAST(10 AS DECIMAL(18,0))
         ELSE CAST(10000 AS DECIMAL(18,0)) END AS USESYSID,
    USER_NAME AS USENAME,
    CLIENT AS APPLICATION_NAME,
    HOST AS CLIENT_ADDR,
    CAST(NULL AS VARCHAR(128)) AS CLIENT_HOSTNAME,
    CAST(NULL AS DECIMAL(18,0)) AS CLIENT_PORT,
    LOGIN_TIME AS BACKEND_START,
    CAST(NULL AS TIMESTAMP) AS XACT_START,
    LOGIN_TIME AS QUERY_START,
    CAST(NULL AS TIMESTAMP) AS STATE_CHANGE,
    CAST(NULL AS VARCHAR(64)) AS WAIT_EVENT_TYPE,
    CAST(NULL AS VARCHAR(128)) AS WAIT_EVENT,
    STATUS AS "STATE",
    CAST(NULL AS DECIMAL(18,0)) AS BACKEND_XID,
    CAST(NULL AS DECIMAL(18,0)) AS BACKEND_XMIN,
    CAST(NULL AS DECIMAL(18,0)) AS QUERY_ID,
    SQL_TEXT AS "QUERY",
    'client backend' AS BACKEND_TYPE
FROM SYS.EXA_DBA_SESSIONS;

CREATE OR REPLACE VIEW PG_CATALOG.PG_REWRITE AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS RULENAME,
    CAST(NULL AS DECIMAL(18,0)) AS EV_CLASS,
    CAST(NULL AS VARCHAR(1)) AS EV_TYPE,
    CAST(NULL AS DECIMAL(18,0)) AS OID
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_RULES AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS SCHEMANAME,
    CAST(NULL AS VARCHAR(128)) AS TABLENAME,
    CAST(NULL AS VARCHAR(128)) AS RULENAME,
    CAST(NULL AS VARCHAR(2000000)) AS DEFINITION
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_TRIGGER AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS TGNAME,
    CAST(NULL AS DECIMAL(18,0)) AS TGRELID,
    CAST(NULL AS DECIMAL(18,0)) AS TGFOID,
    CAST(NULL AS VARCHAR(1)) AS TGENABLED
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_PROC AS
WITH ROLE_LOOKUP AS (
    SELECT OID, ROLNAME
    FROM PG_CATALOG.PG_ROLES
)
SELECT
    F.FUNCTION_OBJECT_ID AS OID,
    F.FUNCTION_NAME AS PRONAME,
    N.OID AS PRONAMESPACE,
    COALESCE(R.OID, CAST(10 AS DECIMAL(18,0))) AS PROOWNER,
    CAST(0 AS DECIMAL(18,0)) AS PROLANG,
    CAST(100 AS DECIMAL(9,0)) AS PROCOST,
    CAST(0 AS DECIMAL(18,0)) AS PROROWS,
    CAST(0 AS DECIMAL(18,0)) AS PROVARIADIC,
    CAST(0 AS DECIMAL(18,0)) AS PROSUPPORT,
    'f' AS PROKIND,
    FALSE AS PROSECDEF,
    FALSE AS PROLEAKPROOF,
    FALSE AS PROISSTRICT,
    FALSE AS PRORETSET,
    'v' AS PROVOLATILE,
    'u' AS PROPARALLEL,
    CAST(0 AS DECIMAL(9,0)) AS PRONARGS,
    CAST(0 AS DECIMAL(9,0)) AS PRONARGDEFAULTS,
    CAST(25 AS DECIMAL(18,0)) AS PRORETTYPE,
    CAST('' AS VARCHAR(2000)) AS PROARGTYPES,
    CAST(NULL AS VARCHAR(2000)) AS PROALLARGTYPES,
    CAST(NULL AS VARCHAR(2000)) AS PROARGMODES,
    CAST(NULL AS VARCHAR(2000)) AS PROARGNAMES,
    CAST(NULL AS VARCHAR(2000000)) AS PROARGDEFAULTS,
    CAST(NULL AS VARCHAR(2000)) AS PROTRFTYPES,
    F.FUNCTION_TEXT AS PROSRC,
    CAST(NULL AS VARCHAR(2000)) AS PROBIN,
    CAST(NULL AS VARCHAR(2000000)) AS PROSQLBODY,
    CAST(NULL AS VARCHAR(2000)) AS PROCONFIG,
    CAST(NULL AS VARCHAR(2000)) AS PROACL
FROM SYS.EXA_DBA_FUNCTIONS F
JOIN PG_CATALOG.PG_NAMESPACE N
  ON N.NSPNAME = F.FUNCTION_SCHEMA
LEFT JOIN ROLE_LOOKUP R
  ON R.ROLNAME = F.FUNCTION_OWNER;

CREATE OR REPLACE VIEW PG_CATALOG.PG_FOREIGN_TABLE AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS FTRELID,
    CAST(NULL AS DECIMAL(18,0)) AS FTSERVER,
    CAST(NULL AS VARCHAR(2000)) AS FTOPTIONS
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_FOREIGN_SERVER AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS OID,
    CAST(NULL AS VARCHAR(128)) AS SRVNAME
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_DEPEND AS
SELECT
    CASE
        WHEN OBJECT_TYPE IN ('TABLE', 'VIEW', 'INDEX') THEN CAST(1259 AS DECIMAL(18,0))
        WHEN OBJECT_TYPE = 'FUNCTION' THEN CAST(1255 AS DECIMAL(18,0))
        WHEN OBJECT_TYPE = 'SCHEMA' THEN CAST(2615 AS DECIMAL(18,0))
        ELSE CAST(0 AS DECIMAL(18,0))
    END AS CLASSID,
    OBJECT_ID AS OBJID,
    CAST(0 AS DECIMAL(18,0)) AS OBJSUBID,
    CASE
        WHEN REFERENCED_OBJECT_TYPE IN ('TABLE', 'VIEW', 'INDEX') THEN CAST(1259 AS DECIMAL(18,0))
        WHEN REFERENCED_OBJECT_TYPE = 'FUNCTION' THEN CAST(1255 AS DECIMAL(18,0))
        WHEN REFERENCED_OBJECT_TYPE = 'SCHEMA' THEN CAST(2615 AS DECIMAL(18,0))
        ELSE CAST(0 AS DECIMAL(18,0))
    END AS REFCLASSID,
    REFERENCED_OBJECT_ID AS REFOBJID,
    CAST(0 AS DECIMAL(18,0)) AS REFOBJSUBID,
    'n' AS DEPTYPE
FROM SYS.EXA_DBA_DEPENDENCIES;

CREATE OR REPLACE VIEW PG_CATALOG.PG_SEQUENCE AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS SEQRELID,
    CAST(NULL AS DECIMAL(18,0)) AS SEQINCREMENT,
    CAST(NULL AS DECIMAL(18,0)) AS SEQMAX,
    CAST(NULL AS DECIMAL(18,0)) AS SEQMIN,
    CAST(NULL AS DECIMAL(18,0)) AS SEQCACHE,
    CAST(NULL AS BOOLEAN) AS SEQCYCLE
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.SCHEMATA AS
SELECT
    'exasol' AS CATALOG_NAME,
    NSPNAME AS SCHEMA_NAME,
    'SYS' AS SCHEMA_OWNER,
    CAST(NULL AS VARCHAR(128)) AS DEFAULT_CHARACTER_SET_CATALOG,
    CAST(NULL AS VARCHAR(128)) AS DEFAULT_CHARACTER_SET_SCHEMA,
    CAST(NULL AS VARCHAR(128)) AS DEFAULT_CHARACTER_SET_NAME,
    CAST(NULL AS VARCHAR(2000)) AS SQL_PATH
FROM PG_CATALOG.PG_NAMESPACE;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.INFORMATION_SCHEMA_CATALOG_NAME AS
SELECT
    'exasol' AS CATALOG_NAME;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.ENABLED_ROLES AS
SELECT
    ROLE_NAME AS ROLE_NAME
FROM (
    SELECT USER_NAME AS ROLE_NAME
    FROM SYS.EXA_DBA_USERS
    UNION
    SELECT GRANTED_ROLE AS ROLE_NAME
    FROM SYS.EXA_DBA_ROLE_PRIVS
    WHERE GRANTEE = 'SYS'
) ROLES
WHERE ROLE_NAME = 'SYS' OR ROLE_NAME = 'DBA';

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.APPLICABLE_ROLES AS
SELECT
    RP.GRANTEE AS GRANTEE,
    RP.GRANTED_ROLE AS ROLE_NAME,
    CASE WHEN COALESCE(RP.ADMIN_OPTION, FALSE) THEN 'YES' ELSE 'NO' END AS IS_GRANTABLE
FROM SYS.EXA_DBA_ROLE_PRIVS RP
UNION ALL
SELECT
    'SYS' AS GRANTEE,
    'SYS' AS ROLE_NAME,
    'YES' AS IS_GRANTABLE;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.ADMINISTRABLE_ROLE_AUTHORIZATIONS AS
SELECT
    GRANTEE,
    ROLE_NAME,
    IS_GRANTABLE
FROM INFORMATION_SCHEMA.APPLICABLE_ROLES
WHERE IS_GRANTABLE = 'YES';

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.TABLES AS
SELECT
    'exasol' AS TABLE_CATALOG,
    TABLE_SCHEMA AS TABLE_SCHEMA,
    TABLE_NAME AS TABLE_NAME,
    'BASE TABLE' AS TABLE_TYPE,
    CAST(NULL AS VARCHAR(128)) AS SELF_REFERENCING_COLUMN_NAME,
    CAST(NULL AS VARCHAR(128)) AS REFERENCE_GENERATION,
    CAST(NULL AS VARCHAR(128)) AS USER_DEFINED_TYPE_CATALOG,
    CAST(NULL AS VARCHAR(128)) AS USER_DEFINED_TYPE_SCHEMA,
    CAST(NULL AS VARCHAR(128)) AS USER_DEFINED_TYPE_NAME,
    'YES' AS IS_INSERTABLE_INTO,
    'NO' AS IS_TYPED,
    CAST(NULL AS VARCHAR(128)) AS COMMIT_ACTION
FROM SYS.EXA_DBA_TABLES
WHERE TABLE_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA')
UNION ALL
SELECT
    'exasol',
    VIEW_SCHEMA,
    VIEW_NAME,
    'VIEW',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    'NO',
    'NO',
    CAST(NULL AS VARCHAR(128))
FROM SYS.EXA_DBA_VIEWS
WHERE VIEW_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.VIEWS AS
SELECT
    'exasol' AS TABLE_CATALOG,
    VIEW_SCHEMA AS TABLE_SCHEMA,
    VIEW_NAME AS TABLE_NAME,
    VIEW_TEXT AS VIEW_DEFINITION,
    'NONE' AS CHECK_OPTION,
    'NO' AS IS_UPDATABLE,
    'NO' AS IS_INSERTABLE_INTO,
    'NO' AS IS_TRIGGER_UPDATABLE,
    'NO' AS IS_TRIGGER_DELETABLE,
    'NO' AS IS_TRIGGER_INSERTABLE_INTO
FROM SYS.EXA_DBA_VIEWS
WHERE VIEW_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.COLUMNS AS
SELECT
    'exasol' AS "TABLE_CATALOG",
    COLUMN_SCHEMA AS "TABLE_SCHEMA",
    COLUMN_TABLE AS "TABLE_NAME",
    COLUMN_NAME AS "COLUMN_NAME",
    COLUMN_ORDINAL_POSITION AS "ORDINAL_POSITION",
    COLUMN_DEFAULT AS "COLUMN_DEFAULT",
    CASE WHEN COLUMN_IS_NULLABLE THEN 'YES' ELSE 'NO' END AS "IS_NULLABLE",
    CASE
        WHEN COLUMN_TYPE LIKE 'DECIMAL(%' THEN 'numeric'
        WHEN COLUMN_TYPE LIKE 'VARCHAR(%' THEN 'character varying'
        WHEN COLUMN_TYPE LIKE 'CHAR(%' THEN 'character'
        WHEN COLUMN_TYPE LIKE 'TIMESTAMP%' THEN 'timestamp without time zone'
        WHEN COLUMN_TYPE = 'DATE' THEN 'date'
        WHEN COLUMN_TYPE = 'BOOLEAN' THEN 'boolean'
        WHEN COLUMN_TYPE IN ('DOUBLE', 'DOUBLE PRECISION') THEN 'double precision'
        WHEN COLUMN_TYPE = 'REAL' THEN 'real'
        ELSE 'text'
    END AS "DATA_TYPE",
    COLUMN_MAXSIZE AS "CHARACTER_MAXIMUM_LENGTH",
    COLUMN_MAXSIZE AS "CHARACTER_OCTET_LENGTH",
    COLUMN_NUM_PREC AS "NUMERIC_PRECISION",
    COLUMN_NUM_SCALE AS "NUMERIC_SCALE",
    CAST(10 AS DECIMAL(9,0)) AS "NUMERIC_PRECISION_RADIX",
    CAST(NULL AS DECIMAL(9,0)) AS "DATETIME_PRECISION",
    CAST(NULL AS VARCHAR(128)) AS "INTERVAL_TYPE",
    CAST(NULL AS DECIMAL(9,0)) AS "INTERVAL_PRECISION",
    CAST(NULL AS VARCHAR(128)) AS "CHARACTER_SET_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "CHARACTER_SET_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "CHARACTER_SET_NAME",
    CAST(NULL AS VARCHAR(128)) AS "COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "COLLATION_NAME",
    'exasol' AS "DOMAIN_CATALOG",
    COLUMN_SCHEMA AS "DOMAIN_SCHEMA",
    CASE
        WHEN COLUMN_TYPE LIKE 'DECIMAL(%' THEN 'numeric'
        WHEN COLUMN_TYPE LIKE 'VARCHAR(%' THEN 'varchar'
        WHEN COLUMN_TYPE LIKE 'CHAR(%' THEN 'bpchar'
        WHEN COLUMN_TYPE LIKE 'TIMESTAMP%' THEN 'timestamp'
        WHEN COLUMN_TYPE = 'DATE' THEN 'date'
        WHEN COLUMN_TYPE = 'BOOLEAN' THEN 'bool'
        WHEN COLUMN_TYPE IN ('DOUBLE', 'DOUBLE PRECISION') THEN 'float8'
        WHEN COLUMN_TYPE = 'REAL' THEN 'float4'
        ELSE 'text'
    END AS "UDT_NAME",
    CAST(NULL AS VARCHAR(128)) AS "SCOPE_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "SCOPE_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "SCOPE_NAME",
    CAST(NULL AS DECIMAL(9,0)) AS "MAXIMUM_CARDINALITY",
    CAST(NULL AS VARCHAR(128)) AS "DTD_IDENTIFIER",
    'NO' AS "IS_SELF_REFERENCING",
    'NO' AS "IS_IDENTITY",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_GENERATION",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_START",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_INCREMENT",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_MAXIMUM",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_MINIMUM",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_CYCLE",
    'NO' AS "IS_GENERATED",
    CAST(NULL AS VARCHAR(2000)) AS "GENERATION_EXPRESSION",
    CASE WHEN COLUMN_IDENTITY IS NULL THEN 'NO' ELSE 'YES' END AS "IS_UPDATABLE"
FROM SYS.EXA_DBA_COLUMNS
WHERE COLUMN_OBJECT_TYPE IN ('TABLE', 'VIEW')
  AND COLUMN_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS
SELECT
    'exasol' AS CONSTRAINT_CATALOG,
    CONSTRAINT_SCHEMA AS CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS CONSTRAINT_NAME,
    'exasol' AS TABLE_CATALOG,
    CONSTRAINT_SCHEMA AS TABLE_SCHEMA,
    CONSTRAINT_TABLE AS TABLE_NAME,
    CASE
        WHEN CONSTRAINT_TYPE = 'PRIMARY KEY' THEN 'PRIMARY KEY'
        WHEN CONSTRAINT_TYPE = 'FOREIGN KEY' THEN 'FOREIGN KEY'
        WHEN CONSTRAINT_TYPE = 'NOT NULL' THEN 'CHECK'
        ELSE CONSTRAINT_TYPE
    END AS CONSTRAINT_TYPE,
    'NO' AS IS_DEFERRABLE,
    'NO' AS INITIALLY_DEFERRED,
    CASE WHEN CONSTRAINT_ENABLED THEN 'YES' ELSE 'NO' END AS ENFORCED,
    'YES' AS NULLS_DISTINCT
FROM SYS.EXA_DBA_CONSTRAINTS;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS
SELECT
    'exasol' AS CONSTRAINT_CATALOG,
    CONSTRAINT_SCHEMA AS CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS CONSTRAINT_NAME,
    'exasol' AS TABLE_CATALOG,
    CONSTRAINT_SCHEMA AS TABLE_SCHEMA,
    CONSTRAINT_TABLE AS TABLE_NAME,
    COLUMN_NAME AS COLUMN_NAME,
    ORDINAL_POSITION AS ORDINAL_POSITION,
    ORDINAL_POSITION AS POSITION_IN_UNIQUE_CONSTRAINT
FROM SYS.EXA_DBA_CONSTRAINT_COLUMNS;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS
SELECT
    'exasol' AS CONSTRAINT_CATALOG,
    CONSTRAINT_SCHEMA AS CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS CONSTRAINT_NAME,
    'exasol' AS UNIQUE_CONSTRAINT_CATALOG,
    REFERENCED_SCHEMA AS UNIQUE_CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS UNIQUE_CONSTRAINT_NAME,
    'NONE' AS MATCH_OPTION,
    'NO ACTION' AS UPDATE_RULE,
    'NO ACTION' AS DELETE_RULE
FROM SYS.EXA_DBA_CONSTRAINT_COLUMNS
WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'
GROUP BY CONSTRAINT_SCHEMA, CONSTRAINT_NAME, REFERENCED_SCHEMA;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.TRIGGERS AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS TRIGGER_CATALOG,
    CAST(NULL AS VARCHAR(128)) AS TRIGGER_SCHEMA,
    CAST(NULL AS VARCHAR(128)) AS TRIGGER_NAME,
    CAST(NULL AS VARCHAR(64)) AS EVENT_MANIPULATION,
    CAST(NULL AS VARCHAR(64)) AS ACTION_ORIENTATION,
    CAST(NULL AS VARCHAR(2000)) AS ACTION_CONDITION,
    CAST(NULL AS VARCHAR(2000000)) AS ACTION_STATEMENT,
    CAST(NULL AS VARCHAR(64)) AS ACTION_TIMING,
    CAST(NULL AS VARCHAR(128)) AS EVENT_OBJECT_CATALOG,
    CAST(NULL AS VARCHAR(128)) AS EVENT_OBJECT_SCHEMA,
    CAST(NULL AS VARCHAR(128)) AS EVENT_OBJECT_TABLE,
    CAST(NULL AS VARCHAR(128)) AS ACTION_REFERENCE_OLD_TABLE,
    CAST(NULL AS VARCHAR(128)) AS ACTION_REFERENCE_NEW_TABLE
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.ROUTINES AS
SELECT
    'exasol' AS "SPECIFIC_CATALOG",
    F.FUNCTION_SCHEMA AS "SPECIFIC_SCHEMA",
    F.FUNCTION_NAME || '_' || CAST(F.FUNCTION_OBJECT_ID AS VARCHAR(20)) AS "SPECIFIC_NAME",
    'exasol' AS "ROUTINE_CATALOG",
    F.FUNCTION_SCHEMA AS "ROUTINE_SCHEMA",
    F.FUNCTION_NAME AS "ROUTINE_NAME",
    'FUNCTION' AS "ROUTINE_TYPE",
    CAST(NULL AS VARCHAR(128)) AS "MODULE_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "MODULE_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "MODULE_NAME",
    CAST(NULL AS VARCHAR(128)) AS "UDT_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "UDT_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "UDT_NAME",
    'text' AS "DATA_TYPE",
    CAST(NULL AS DECIMAL(18,0)) AS "CHARACTER_MAXIMUM_LENGTH",
    CAST(NULL AS DECIMAL(18,0)) AS "CHARACTER_OCTET_LENGTH",
    CAST(NULL AS VARCHAR(128)) AS "CHARACTER_SET_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "CHARACTER_SET_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "CHARACTER_SET_NAME",
    CAST(NULL AS VARCHAR(128)) AS "COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "COLLATION_NAME",
    CAST(NULL AS DECIMAL(18,0)) AS "NUMERIC_PRECISION",
    CAST(NULL AS DECIMAL(18,0)) AS "NUMERIC_PRECISION_RADIX",
    CAST(NULL AS DECIMAL(18,0)) AS "NUMERIC_SCALE",
    CAST(NULL AS DECIMAL(18,0)) AS "DATETIME_PRECISION",
    CAST(NULL AS VARCHAR(128)) AS "INTERVAL_TYPE",
    CAST(NULL AS DECIMAL(18,0)) AS "INTERVAL_PRECISION",
    'exasol' AS "TYPE_UDT_CATALOG",
    F.FUNCTION_SCHEMA AS "TYPE_UDT_SCHEMA",
    'text' AS "TYPE_UDT_NAME",
    CAST(NULL AS VARCHAR(128)) AS "SCOPE_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "SCOPE_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "SCOPE_NAME",
    CAST(NULL AS DECIMAL(18,0)) AS "MAXIMUM_CARDINALITY",
    CAST(NULL AS VARCHAR(128)) AS "DTD_IDENTIFIER",
    'SQL' AS "ROUTINE_BODY",
    F.FUNCTION_TEXT AS "ROUTINE_DEFINITION",
    CAST(NULL AS VARCHAR(128)) AS "EXTERNAL_NAME",
    'SQL' AS "EXTERNAL_LANGUAGE",
    'SQL' AS "PARAMETER_STYLE",
    'NO' AS "IS_DETERMINISTIC",
    'MODIFIES' AS "SQL_DATA_ACCESS",
    'NO' AS "IS_NULL_CALL",
    CAST(NULL AS VARCHAR(2000)) AS "SQL_PATH",
    'YES' AS "SCHEMA_LEVEL_ROUTINE",
    CAST(0 AS DECIMAL(18,0)) AS "MAX_DYNAMIC_RESULT_SETS",
    'NO' AS "IS_USER_DEFINED_CAST",
    'NO' AS "IS_IMPLICITLY_INVOCABLE",
    'INVOKER' AS "SECURITY_TYPE",
    CAST(NULL AS VARCHAR(128)) AS "TO_SQL_SPECIFIC_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "TO_SQL_SPECIFIC_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "TO_SQL_SPECIFIC_NAME",
    'NO' AS "AS_LOCATOR",
    O.CREATED AS "CREATED",
    O.LAST_COMMIT AS "LAST_ALTERED",
    'NO' AS "NEW_SAVEPOINT_LEVEL",
    'NO' AS "IS_UDT_DEPENDENT",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_FROM_DATA_TYPE",
    'NO' AS "RESULT_CAST_AS_LOCATOR",
    CAST(NULL AS DECIMAL(18,0)) AS "RESULT_CAST_CHAR_MAX_LENGTH",
    CAST(NULL AS DECIMAL(18,0)) AS "RESULT_CAST_CHAR_OCTET_LENGTH",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_CHAR_SET_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_CHAR_SET_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_CHAR_SET_NAME",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_COLLATION_NAME",
    CAST(NULL AS DECIMAL(18,0)) AS "RESULT_CAST_NUMERIC_PRECISION",
    CAST(NULL AS DECIMAL(18,0)) AS "RESULT_CAST_NUMERIC_PRECISION_RADIX",
    CAST(NULL AS DECIMAL(18,0)) AS "RESULT_CAST_NUMERIC_SCALE",
    CAST(NULL AS DECIMAL(18,0)) AS "RESULT_CAST_DATETIME_PRECISION",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_INTERVAL_TYPE",
    CAST(NULL AS DECIMAL(18,0)) AS "RESULT_CAST_INTERVAL_PRECISION",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_TYPE_UDT_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_TYPE_UDT_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_TYPE_UDT_NAME",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_SCOPE_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_SCOPE_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_SCOPE_NAME",
    CAST(NULL AS DECIMAL(18,0)) AS "RESULT_CAST_MAXIMUM_CARDINALITY",
    CAST(NULL AS VARCHAR(128)) AS "RESULT_CAST_DTD_IDENTIFIER"
FROM SYS.EXA_DBA_FUNCTIONS F
LEFT JOIN SYS.EXA_DBA_OBJECTS O
  ON O.OBJECT_ID = F.FUNCTION_OBJECT_ID;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE AS
SELECT
    'exasol' AS TABLE_CATALOG,
    CONSTRAINT_SCHEMA AS TABLE_SCHEMA,
    CONSTRAINT_TABLE AS TABLE_NAME,
    COLUMN_NAME AS COLUMN_NAME,
    'exasol' AS CONSTRAINT_CATALOG,
    CONSTRAINT_SCHEMA AS CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS CONSTRAINT_NAME
FROM SYS.EXA_DBA_CONSTRAINT_COLUMNS;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.CONSTRAINT_TABLE_USAGE AS
SELECT
    'exasol' AS TABLE_CATALOG,
    CONSTRAINT_SCHEMA AS TABLE_SCHEMA,
    CONSTRAINT_TABLE AS TABLE_NAME,
    'exasol' AS CONSTRAINT_CATALOG,
    CONSTRAINT_SCHEMA AS CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS CONSTRAINT_NAME
FROM SYS.EXA_DBA_CONSTRAINTS
UNION ALL
SELECT
    'exasol' AS TABLE_CATALOG,
    REFERENCED_SCHEMA AS TABLE_SCHEMA,
    REFERENCED_TABLE AS TABLE_NAME,
    'exasol' AS CONSTRAINT_CATALOG,
    CONSTRAINT_SCHEMA AS CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS CONSTRAINT_NAME
FROM SYS.EXA_DBA_CONSTRAINT_COLUMNS
WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'
  AND REFERENCED_SCHEMA IS NOT NULL
  AND REFERENCED_TABLE IS NOT NULL;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.ROLE_ROUTINE_GRANTS AS
SELECT
    GRANTOR AS GRANTOR,
    GRANTEE AS GRANTEE,
    'exasol' AS SPECIFIC_CATALOG,
    OBJECT_SCHEMA AS SPECIFIC_SCHEMA,
    OBJECT_NAME AS SPECIFIC_NAME,
    'exasol' AS ROUTINE_CATALOG,
    OBJECT_SCHEMA AS ROUTINE_SCHEMA,
    OBJECT_NAME AS ROUTINE_NAME,
    PRIVILEGE AS PRIVILEGE_TYPE,
    'NO' AS IS_GRANTABLE
FROM SYS.EXA_DBA_OBJ_PRIVS
WHERE OBJECT_TYPE = 'FUNCTION';

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.ROLE_TABLE_GRANTS AS
SELECT
    GRANTOR AS GRANTOR,
    GRANTEE AS GRANTEE,
    'exasol' AS TABLE_CATALOG,
    OBJECT_SCHEMA AS TABLE_SCHEMA,
    OBJECT_NAME AS TABLE_NAME,
    PRIVILEGE AS PRIVILEGE_TYPE,
    'NO' AS IS_GRANTABLE,
    'NO' AS WITH_HIERARCHY
FROM SYS.EXA_DBA_OBJ_PRIVS
WHERE OBJECT_TYPE IN ('TABLE', 'VIEW');

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.ROUTINE_TABLE_USAGE AS
SELECT
    'exasol' AS SPECIFIC_CATALOG,
    OBJECT_SCHEMA AS SPECIFIC_SCHEMA,
    OBJECT_NAME || '_' || CAST(OBJECT_ID AS VARCHAR(20)) AS SPECIFIC_NAME,
    'exasol' AS ROUTINE_CATALOG,
    OBJECT_SCHEMA AS ROUTINE_SCHEMA,
    OBJECT_NAME AS ROUTINE_NAME,
    'exasol' AS TABLE_CATALOG,
    REFERENCED_OBJECT_SCHEMA AS TABLE_SCHEMA,
    REFERENCED_OBJECT_NAME AS TABLE_NAME
FROM SYS.EXA_DBA_DEPENDENCIES
WHERE OBJECT_TYPE = 'FUNCTION'
  AND REFERENCED_OBJECT_TYPE IN ('TABLE', 'VIEW');

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.TABLE_PRIVILEGES AS
SELECT
    GRANTOR AS GRANTOR,
    GRANTEE AS GRANTEE,
    'exasol' AS TABLE_CATALOG,
    OBJECT_SCHEMA AS TABLE_SCHEMA,
    OBJECT_NAME AS TABLE_NAME,
    PRIVILEGE AS PRIVILEGE_TYPE,
    'NO' AS IS_GRANTABLE,
    'NO' AS WITH_HIERARCHY
FROM SYS.EXA_DBA_OBJ_PRIVS
WHERE OBJECT_TYPE IN ('TABLE', 'VIEW');

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.VIEW_TABLE_USAGE AS
SELECT
    'exasol' AS VIEW_CATALOG,
    OBJECT_SCHEMA AS VIEW_SCHEMA,
    OBJECT_NAME AS VIEW_NAME,
    'exasol' AS TABLE_CATALOG,
    REFERENCED_OBJECT_SCHEMA AS TABLE_SCHEMA,
    REFERENCED_OBJECT_NAME AS TABLE_NAME
FROM SYS.EXA_DBA_DEPENDENCIES
WHERE OBJECT_TYPE = 'VIEW'
  AND REFERENCED_OBJECT_TYPE IN ('TABLE', 'VIEW');

-- GENERATED_PLACEHOLDER_VIEWS_START
-- Generated from PostgreSQL 18 catalog and information schema documentation.

CREATE OR REPLACE VIEW PG_CATALOG."PG_AGGREGATE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "AGGFNOID",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGKIND",
    CAST(NULL AS DECIMAL(36,0)) AS "AGGNUMDIRECTARGS",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGTRANSFN",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGFINALFN",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGCOMBINEFN",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGSERIALFN",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGDESERIALFN",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGMTRANSFN",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGMINVTRANSFN",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGMFINALFN",
    CAST(NULL AS BOOLEAN) AS "AGGFINALEXTRA",
    CAST(NULL AS BOOLEAN) AS "AGGMFINALEXTRA",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGFINALMODIFY",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGMFINALMODIFY",
    CAST(NULL AS DECIMAL(36,0)) AS "AGGSORTOP",
    CAST(NULL AS DECIMAL(36,0)) AS "AGGTRANSTYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "AGGTRANSSPACE",
    CAST(NULL AS DECIMAL(36,0)) AS "AGGMTRANSTYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "AGGMTRANSSPACE",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGINITVAL",
    CAST(NULL AS VARCHAR(2000000)) AS "AGGMINITVAL"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_AMOP" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "AMOPFAMILY",
    CAST(NULL AS DECIMAL(36,0)) AS "AMOPLEFTTYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "AMOPRIGHTTYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "AMOPSTRATEGY",
    CAST(NULL AS VARCHAR(2000000)) AS "AMOPPURPOSE",
    CAST(NULL AS DECIMAL(36,0)) AS "AMOPOPR",
    CAST(NULL AS DECIMAL(36,0)) AS "AMOPMETHOD",
    CAST(NULL AS DECIMAL(36,0)) AS "AMOPSORTFAMILY"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_AMPROC" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "AMPROCFAMILY",
    CAST(NULL AS DECIMAL(36,0)) AS "AMPROCLEFTTYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "AMPROCRIGHTTYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "AMPROCNUM",
    CAST(NULL AS VARCHAR(2000000)) AS "AMPROC"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_CAST" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "CASTSOURCE",
    CAST(NULL AS DECIMAL(36,0)) AS "CASTTARGET",
    CAST(NULL AS DECIMAL(36,0)) AS "CASTFUNC",
    CAST(NULL AS VARCHAR(2000000)) AS "CASTCONTEXT",
    CAST(NULL AS VARCHAR(2000000)) AS "CASTMETHOD"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_COLLATION" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "COLLNAMESPACE",
    CAST(NULL AS DECIMAL(36,0)) AS "COLLOWNER",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLPROVIDER",
    CAST(NULL AS BOOLEAN) AS "COLLISDETERMINISTIC",
    CAST(NULL AS DECIMAL(36,0)) AS "COLLENCODING",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLCOLLATE",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLCTYPE",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLLOCALE",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLICURULES",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLVERSION"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_CONVERSION" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "CONNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "CONNAMESPACE",
    CAST(NULL AS DECIMAL(36,0)) AS "CONOWNER",
    CAST(NULL AS DECIMAL(36,0)) AS "CONFORENCODING",
    CAST(NULL AS DECIMAL(36,0)) AS "CONTOENCODING",
    CAST(NULL AS VARCHAR(2000000)) AS "CONPROC",
    CAST(NULL AS BOOLEAN) AS "CONDEFAULT"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_DB_ROLE_SETTING" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "SETDATABASE",
    CAST(NULL AS DECIMAL(36,0)) AS "SETROLE",
    CAST(NULL AS VARCHAR(2000000)) AS "SETCONFIG"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_DEFAULT_ACL" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "DEFACLROLE",
    CAST(NULL AS DECIMAL(36,0)) AS "DEFACLNAMESPACE",
    CAST(NULL AS VARCHAR(2000000)) AS "DEFACLOBJTYPE",
    CAST(NULL AS VARCHAR(2000000)) AS "DEFACLACL"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_ENUM" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "ENUMTYPID",
    CAST(NULL AS DOUBLE) AS "ENUMSORTORDER",
    CAST(NULL AS VARCHAR(2000000)) AS "ENUMLABEL"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_EVENT_TRIGGER" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "EVTNAME",
    CAST(NULL AS VARCHAR(2000000)) AS "EVTEVENT",
    CAST(NULL AS DECIMAL(36,0)) AS "EVTOWNER",
    CAST(NULL AS DECIMAL(36,0)) AS "EVTFOID",
    CAST(NULL AS VARCHAR(2000000)) AS "EVTENABLED",
    CAST(NULL AS VARCHAR(2000000)) AS "EVTTAGS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_EXTENSION" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "EXTNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "EXTOWNER",
    CAST(NULL AS DECIMAL(36,0)) AS "EXTNAMESPACE",
    CAST(NULL AS BOOLEAN) AS "EXTRELOCATABLE",
    CAST(NULL AS VARCHAR(2000000)) AS "EXTVERSION",
    CAST(NULL AS VARCHAR(2000000)) AS "EXTCONFIG",
    CAST(NULL AS VARCHAR(2000000)) AS "EXTCONDITION"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_FOREIGN_DATA_WRAPPER" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "FDWNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "FDWOWNER",
    CAST(NULL AS DECIMAL(36,0)) AS "FDWHANDLER",
    CAST(NULL AS DECIMAL(36,0)) AS "FDWVALIDATOR",
    CAST(NULL AS VARCHAR(2000000)) AS "FDWACL",
    CAST(NULL AS VARCHAR(2000000)) AS "FDWOPTIONS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_INHERITS" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "INHRELID",
    CAST(NULL AS DECIMAL(36,0)) AS "INHPARENT",
    CAST(NULL AS DECIMAL(36,0)) AS "INHSEQNO",
    CAST(NULL AS BOOLEAN) AS "INHDETACHPENDING"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_INIT_PRIVS" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OBJOID",
    CAST(NULL AS DECIMAL(36,0)) AS "CLASSOID",
    CAST(NULL AS DECIMAL(36,0)) AS "OBJSUBID",
    CAST(NULL AS VARCHAR(2000000)) AS "PRIVTYPE",
    CAST(NULL AS VARCHAR(2000000)) AS "INITPRIVS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_LANGUAGE" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "LANNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "LANOWNER",
    CAST(NULL AS BOOLEAN) AS "LANISPL",
    CAST(NULL AS BOOLEAN) AS "LANPLTRUSTED",
    CAST(NULL AS DECIMAL(36,0)) AS "LANPLCALLFOID",
    CAST(NULL AS DECIMAL(36,0)) AS "LANINLINE",
    CAST(NULL AS DECIMAL(36,0)) AS "LANVALIDATOR",
    CAST(NULL AS VARCHAR(2000000)) AS "LANACL"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_LARGEOBJECT" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "LOID",
    CAST(NULL AS DECIMAL(36,0)) AS "PAGENO",
    CAST(NULL AS VARCHAR(2000000)) AS "DATA"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_LARGEOBJECT_METADATA" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "LOMOWNER",
    CAST(NULL AS VARCHAR(2000000)) AS "LOMACL"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_OPCLASS" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "OPCMETHOD",
    CAST(NULL AS VARCHAR(2000000)) AS "OPCNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "OPCNAMESPACE",
    CAST(NULL AS DECIMAL(36,0)) AS "OPCOWNER",
    CAST(NULL AS DECIMAL(36,0)) AS "OPCFAMILY",
    CAST(NULL AS DECIMAL(36,0)) AS "OPCINTYPE",
    CAST(NULL AS BOOLEAN) AS "OPCDEFAULT",
    CAST(NULL AS DECIMAL(36,0)) AS "OPCKEYTYPE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_OPERATOR" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "OPRNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "OPRNAMESPACE",
    CAST(NULL AS DECIMAL(36,0)) AS "OPROWNER",
    CAST(NULL AS VARCHAR(2000000)) AS "OPRKIND",
    CAST(NULL AS BOOLEAN) AS "OPRCANMERGE",
    CAST(NULL AS BOOLEAN) AS "OPRCANHASH",
    CAST(NULL AS DECIMAL(36,0)) AS "OPRLEFT",
    CAST(NULL AS DECIMAL(36,0)) AS "OPRRIGHT",
    CAST(NULL AS DECIMAL(36,0)) AS "OPRRESULT",
    CAST(NULL AS DECIMAL(36,0)) AS "OPRCOM",
    CAST(NULL AS DECIMAL(36,0)) AS "OPRNEGATE",
    CAST(NULL AS VARCHAR(2000000)) AS "OPRCODE",
    CAST(NULL AS VARCHAR(2000000)) AS "OPRREST",
    CAST(NULL AS VARCHAR(2000000)) AS "OPRJOIN"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_OPFAMILY" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "OPFMETHOD",
    CAST(NULL AS VARCHAR(2000000)) AS "OPFNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "OPFNAMESPACE",
    CAST(NULL AS DECIMAL(36,0)) AS "OPFOWNER"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_PARAMETER_ACL" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "PARNAME",
    CAST(NULL AS VARCHAR(2000000)) AS "PARACL"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_PARTITIONED_TABLE" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "PARTRELID",
    CAST(NULL AS VARCHAR(2000000)) AS "PARTSTRAT",
    CAST(NULL AS DECIMAL(36,0)) AS "PARTNATTS",
    CAST(NULL AS DECIMAL(36,0)) AS "PARTDEFID",
    CAST(NULL AS DECIMAL(36,0)) AS "PARTATTRS",
    CAST(NULL AS DECIMAL(36,0)) AS "PARTCLASS",
    CAST(NULL AS DECIMAL(36,0)) AS "PARTCOLLATION",
    CAST(NULL AS VARCHAR(2000000)) AS "PARTEXPRS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_POLICY" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "POLNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "POLRELID",
    CAST(NULL AS VARCHAR(2000000)) AS "POLCMD",
    CAST(NULL AS BOOLEAN) AS "POLPERMISSIVE",
    CAST(NULL AS VARCHAR(2000000)) AS "POLROLES",
    CAST(NULL AS VARCHAR(2000000)) AS "POLQUAL",
    CAST(NULL AS VARCHAR(2000000)) AS "POLWITHCHECK"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_PUBLICATION" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "PUBNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "PUBOWNER",
    CAST(NULL AS BOOLEAN) AS "PUBALLTABLES",
    CAST(NULL AS BOOLEAN) AS "PUBINSERT",
    CAST(NULL AS BOOLEAN) AS "PUBUPDATE",
    CAST(NULL AS BOOLEAN) AS "PUBDELETE",
    CAST(NULL AS BOOLEAN) AS "PUBTRUNCATE",
    CAST(NULL AS BOOLEAN) AS "PUBVIAROOT",
    CAST(NULL AS VARCHAR(2000000)) AS "PUBGENCOLS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_PUBLICATION_NAMESPACE" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "PNPUBID",
    CAST(NULL AS DECIMAL(36,0)) AS "PNNSPID"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_PUBLICATION_REL" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "PRPUBID",
    CAST(NULL AS DECIMAL(36,0)) AS "PRRELID",
    CAST(NULL AS VARCHAR(2000000)) AS "PRQUAL",
    CAST(NULL AS DECIMAL(36,0)) AS "PRATTRS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_RANGE" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "RNGTYPID",
    CAST(NULL AS DECIMAL(36,0)) AS "RNGSUBTYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "RNGMULTITYPID",
    CAST(NULL AS DECIMAL(36,0)) AS "RNGCOLLATION",
    CAST(NULL AS DECIMAL(36,0)) AS "RNGSUBOPC",
    CAST(NULL AS VARCHAR(2000000)) AS "RNGCANONICAL",
    CAST(NULL AS VARCHAR(2000000)) AS "RNGSUBDIFF"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_REPLICATION_ORIGIN" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "ROIDENT",
    CAST(NULL AS VARCHAR(2000000)) AS "RONAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_SECLABEL" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OBJOID",
    CAST(NULL AS DECIMAL(36,0)) AS "CLASSOID",
    CAST(NULL AS DECIMAL(36,0)) AS "OBJSUBID",
    CAST(NULL AS VARCHAR(2000000)) AS "PROVIDER",
    CAST(NULL AS VARCHAR(2000000)) AS "LABEL"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_SHDEPEND" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "DBID",
    CAST(NULL AS DECIMAL(36,0)) AS "CLASSID",
    CAST(NULL AS DECIMAL(36,0)) AS "OBJID",
    CAST(NULL AS DECIMAL(36,0)) AS "OBJSUBID",
    CAST(NULL AS DECIMAL(36,0)) AS "REFCLASSID",
    CAST(NULL AS DECIMAL(36,0)) AS "REFOBJID",
    CAST(NULL AS VARCHAR(2000000)) AS "DEPTYPE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_SHDESCRIPTION" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OBJOID",
    CAST(NULL AS DECIMAL(36,0)) AS "CLASSOID",
    CAST(NULL AS VARCHAR(2000000)) AS "DESCRIPTION"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_SHSECLABEL" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OBJOID",
    CAST(NULL AS DECIMAL(36,0)) AS "CLASSOID",
    CAST(NULL AS VARCHAR(2000000)) AS "PROVIDER",
    CAST(NULL AS VARCHAR(2000000)) AS "LABEL"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_STATISTIC" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "STARELID",
    CAST(NULL AS DECIMAL(36,0)) AS "STAATTNUM",
    CAST(NULL AS BOOLEAN) AS "STAINHERIT",
    CAST(NULL AS DOUBLE) AS "STANULLFRAC",
    CAST(NULL AS DECIMAL(36,0)) AS "STAWIDTH",
    CAST(NULL AS DOUBLE) AS "STADISTINCT",
    CAST(NULL AS DECIMAL(36,0)) AS "STAKIND_N",
    CAST(NULL AS DECIMAL(36,0)) AS "STAOP_N",
    CAST(NULL AS DECIMAL(36,0)) AS "STACOLL_N",
    CAST(NULL AS DOUBLE) AS "STANUMBERS_N",
    CAST(NULL AS VARCHAR(2000000)) AS "STAVALUES_N"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_STATISTIC_EXT" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "STXRELID",
    CAST(NULL AS VARCHAR(2000000)) AS "STXNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "STXNAMESPACE",
    CAST(NULL AS DECIMAL(36,0)) AS "STXOWNER",
    CAST(NULL AS DECIMAL(36,0)) AS "STXKEYS",
    CAST(NULL AS DECIMAL(36,0)) AS "STXSTATTARGET",
    CAST(NULL AS VARCHAR(2000000)) AS "STXKIND",
    CAST(NULL AS VARCHAR(2000000)) AS "STXEXPRS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_STATISTIC_EXT_DATA" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "STXOID",
    CAST(NULL AS BOOLEAN) AS "STXDINHERIT",
    CAST(NULL AS VARCHAR(2000000)) AS "STXDNDISTINCT",
    CAST(NULL AS VARCHAR(2000000)) AS "STXDDEPENDENCIES",
    CAST(NULL AS VARCHAR(2000000)) AS "STXDMCV",
    CAST(NULL AS VARCHAR(2000000)) AS "STXDEXPR"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_SUBSCRIPTION" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "SUBDBID",
    CAST(NULL AS VARCHAR(2000000)) AS "SUBSKIPLSN",
    CAST(NULL AS VARCHAR(2000000)) AS "SUBNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "SUBOWNER",
    CAST(NULL AS BOOLEAN) AS "SUBENABLED",
    CAST(NULL AS BOOLEAN) AS "SUBBINARY",
    CAST(NULL AS VARCHAR(2000000)) AS "SUBSTREAM",
    CAST(NULL AS VARCHAR(2000000)) AS "SUBTWOPHASESTATE",
    CAST(NULL AS BOOLEAN) AS "SUBDISABLEONERR",
    CAST(NULL AS BOOLEAN) AS "SUBPASSWORDREQUIRED",
    CAST(NULL AS BOOLEAN) AS "SUBRUNASOWNER",
    CAST(NULL AS BOOLEAN) AS "SUBFAILOVER",
    CAST(NULL AS VARCHAR(2000000)) AS "SUBCONNINFO",
    CAST(NULL AS VARCHAR(2000000)) AS "SUBSLOTNAME",
    CAST(NULL AS VARCHAR(2000000)) AS "SUBSYNCCOMMIT",
    CAST(NULL AS VARCHAR(2000000)) AS "SUBPUBLICATIONS",
    CAST(NULL AS VARCHAR(2000000)) AS "SUBORIGIN"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_SUBSCRIPTION_REL" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "SRSUBID",
    CAST(NULL AS DECIMAL(36,0)) AS "SRRELID",
    CAST(NULL AS VARCHAR(2000000)) AS "SRSUBSTATE",
    CAST(NULL AS VARCHAR(2000000)) AS "SRSUBLSN"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_TRANSFORM" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "TRFTYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "TRFLANG",
    CAST(NULL AS VARCHAR(2000000)) AS "TRFFROMSQL",
    CAST(NULL AS VARCHAR(2000000)) AS "TRFTOSQL"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_TS_CONFIG" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "CFGNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "CFGNAMESPACE",
    CAST(NULL AS DECIMAL(36,0)) AS "CFGOWNER",
    CAST(NULL AS DECIMAL(36,0)) AS "CFGPARSER"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_TS_CONFIG_MAP" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "MAPCFG",
    CAST(NULL AS DECIMAL(36,0)) AS "MAPTOKENTYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "MAPSEQNO",
    CAST(NULL AS DECIMAL(36,0)) AS "MAPDICT"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_TS_DICT" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "DICTNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "DICTNAMESPACE",
    CAST(NULL AS DECIMAL(36,0)) AS "DICTOWNER",
    CAST(NULL AS DECIMAL(36,0)) AS "DICTTEMPLATE",
    CAST(NULL AS VARCHAR(2000000)) AS "DICTINITOPTION"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_TS_PARSER" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "PRSNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "PRSNAMESPACE",
    CAST(NULL AS VARCHAR(2000000)) AS "PRSSTART",
    CAST(NULL AS VARCHAR(2000000)) AS "PRSTOKEN",
    CAST(NULL AS VARCHAR(2000000)) AS "PRSEND",
    CAST(NULL AS VARCHAR(2000000)) AS "PRSHEADLINE",
    CAST(NULL AS VARCHAR(2000000)) AS "PRSLEXTYPE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_TS_TEMPLATE" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS VARCHAR(2000000)) AS "TMPLNAME",
    CAST(NULL AS DECIMAL(36,0)) AS "TMPLNAMESPACE",
    CAST(NULL AS VARCHAR(2000000)) AS "TMPLINIT",
    CAST(NULL AS VARCHAR(2000000)) AS "TMPLLEXIZE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG."PG_USER_MAPPING" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "OID",
    CAST(NULL AS DECIMAL(36,0)) AS "UMUSER",
    CAST(NULL AS DECIMAL(36,0)) AS "UMSERVER",
    CAST(NULL AS VARCHAR(2000000)) AS "UMOPTIONS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."ATTRIBUTES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "ATTRIBUTE_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "ORDINAL_POSITION",
    CAST(NULL AS VARCHAR(2000000)) AS "ATTRIBUTE_DEFAULT",
    CAST(NULL AS VARCHAR(3)) AS "IS_NULLABLE",
    CAST(NULL AS VARCHAR(2000000)) AS "DATA_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "CHARACTER_MAXIMUM_LENGTH",
    CAST(NULL AS DECIMAL(36,0)) AS "CHARACTER_OCTET_LENGTH",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION_RADIX",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_SCALE",
    CAST(NULL AS DECIMAL(36,0)) AS "DATETIME_PRECISION",
    CAST(NULL AS VARCHAR(2000000)) AS "INTERVAL_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "INTERVAL_PRECISION",
    CAST(NULL AS VARCHAR(2000000)) AS "ATTRIBUTE_UDT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "ATTRIBUTE_UDT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "ATTRIBUTE_UDT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "MAXIMUM_CARDINALITY",
    CAST(NULL AS VARCHAR(2000000)) AS "DTD_IDENTIFIER",
    CAST(NULL AS VARCHAR(3)) AS "IS_DERIVED_REFERENCE_ATTRIBUTE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."CHARACTER_SETS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_REPERTOIRE",
    CAST(NULL AS VARCHAR(2000000)) AS "FORM_OF_USE",
    CAST(NULL AS VARCHAR(2000000)) AS "DEFAULT_COLLATE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "DEFAULT_COLLATE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "DEFAULT_COLLATE_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."CHECK_CONSTRAINT_ROUTINE_USAGE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "CONSTRAINT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "CONSTRAINT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "CONSTRAINT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."CHECK_CONSTRAINTS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "CONSTRAINT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "CONSTRAINT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "CONSTRAINT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "CHECK_CLAUSE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."COLLATIONS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "PAD_ATTRIBUTE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."COLLATION_CHARACTER_SET_APPLICABILITY" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."COLUMN_COLUMN_USAGE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLUMN_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "DEPENDENT_COLUMN"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."COLUMN_DOMAIN_USAGE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLUMN_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."COLUMN_OPTIONS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLUMN_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OPTION_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OPTION_VALUE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."COLUMN_PRIVILEGES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTOR",
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTEE",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLUMN_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "PRIVILEGE_TYPE",
    CAST(NULL AS VARCHAR(3)) AS "IS_GRANTABLE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."COLUMN_UDT_USAGE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLUMN_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."DATA_TYPE_PRIVILEGES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_TYPE",
    CAST(NULL AS VARCHAR(2000000)) AS "DTD_IDENTIFIER"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."DOMAIN_CONSTRAINTS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "CONSTRAINT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "CONSTRAINT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "CONSTRAINT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_NAME",
    CAST(NULL AS VARCHAR(3)) AS "IS_DEFERRABLE",
    CAST(NULL AS VARCHAR(3)) AS "INITIALLY_DEFERRED"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."DOMAIN_UDT_USAGE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."DOMAINS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "DATA_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "CHARACTER_MAXIMUM_LENGTH",
    CAST(NULL AS DECIMAL(36,0)) AS "CHARACTER_OCTET_LENGTH",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION_RADIX",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_SCALE",
    CAST(NULL AS DECIMAL(36,0)) AS "DATETIME_PRECISION",
    CAST(NULL AS VARCHAR(2000000)) AS "INTERVAL_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "INTERVAL_PRECISION",
    CAST(NULL AS VARCHAR(2000000)) AS "DOMAIN_DEFAULT",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "MAXIMUM_CARDINALITY",
    CAST(NULL AS VARCHAR(2000000)) AS "DTD_IDENTIFIER"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."ELEMENT_TYPES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_TYPE",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLECTION_TYPE_IDENTIFIER",
    CAST(NULL AS VARCHAR(2000000)) AS "DATA_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "CHARACTER_MAXIMUM_LENGTH",
    CAST(NULL AS DECIMAL(36,0)) AS "CHARACTER_OCTET_LENGTH",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION_RADIX",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_SCALE",
    CAST(NULL AS DECIMAL(36,0)) AS "DATETIME_PRECISION",
    CAST(NULL AS VARCHAR(2000000)) AS "INTERVAL_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "INTERVAL_PRECISION",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "MAXIMUM_CARDINALITY",
    CAST(NULL AS VARCHAR(2000000)) AS "DTD_IDENTIFIER"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."FOREIGN_DATA_WRAPPER_OPTIONS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_DATA_WRAPPER_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_DATA_WRAPPER_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OPTION_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OPTION_VALUE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."FOREIGN_DATA_WRAPPERS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_DATA_WRAPPER_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_DATA_WRAPPER_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "AUTHORIZATION_IDENTIFIER",
    CAST(NULL AS VARCHAR(2000000)) AS "LIBRARY_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_DATA_WRAPPER_LANGUAGE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."FOREIGN_SERVER_OPTIONS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OPTION_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OPTION_VALUE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."FOREIGN_SERVERS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_DATA_WRAPPER_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_DATA_WRAPPER_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_TYPE",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_VERSION",
    CAST(NULL AS VARCHAR(2000000)) AS "AUTHORIZATION_IDENTIFIER"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."FOREIGN_TABLE_OPTIONS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OPTION_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OPTION_VALUE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."FOREIGN_TABLES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."PARAMETERS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "ORDINAL_POSITION",
    CAST(NULL AS VARCHAR(2000000)) AS "PARAMETER_MODE",
    CAST(NULL AS VARCHAR(3)) AS "IS_RESULT",
    CAST(NULL AS VARCHAR(3)) AS "AS_LOCATOR",
    CAST(NULL AS VARCHAR(2000000)) AS "PARAMETER_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "DATA_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "CHARACTER_MAXIMUM_LENGTH",
    CAST(NULL AS DECIMAL(36,0)) AS "CHARACTER_OCTET_LENGTH",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION_RADIX",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_SCALE",
    CAST(NULL AS DECIMAL(36,0)) AS "DATETIME_PRECISION",
    CAST(NULL AS VARCHAR(2000000)) AS "INTERVAL_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "INTERVAL_PRECISION",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SCOPE_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "MAXIMUM_CARDINALITY",
    CAST(NULL AS VARCHAR(2000000)) AS "DTD_IDENTIFIER",
    CAST(NULL AS VARCHAR(2000000)) AS "PARAMETER_DEFAULT"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."ROLE_COLUMN_GRANTS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTOR",
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTEE",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLUMN_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "PRIVILEGE_TYPE",
    CAST(NULL AS VARCHAR(3)) AS "IS_GRANTABLE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."ROLE_UDT_GRANTS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTOR",
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTEE",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "PRIVILEGE_TYPE",
    CAST(NULL AS VARCHAR(3)) AS "IS_GRANTABLE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."ROLE_USAGE_GRANTS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTOR",
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTEE",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_TYPE",
    CAST(NULL AS VARCHAR(2000000)) AS "PRIVILEGE_TYPE",
    CAST(NULL AS VARCHAR(3)) AS "IS_GRANTABLE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."ROUTINE_COLUMN_USAGE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLUMN_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."ROUTINE_PRIVILEGES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTOR",
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTEE",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "PRIVILEGE_TYPE",
    CAST(NULL AS VARCHAR(3)) AS "IS_GRANTABLE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."ROUTINE_ROUTINE_USAGE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."ROUTINE_SEQUENCE_USAGE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "ROUTINE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "SCHEMA_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SEQUENCE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SEQUENCE_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."SEQUENCES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "SEQUENCE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SEQUENCE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SEQUENCE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "DATA_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION_RADIX",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_SCALE",
    CAST(NULL AS VARCHAR(2000000)) AS "START_VALUE",
    CAST(NULL AS VARCHAR(2000000)) AS "MINIMUM_VALUE",
    CAST(NULL AS VARCHAR(2000000)) AS "MAXIMUM_VALUE",
    CAST(NULL AS VARCHAR(2000000)) AS "INCREMENT",
    CAST(NULL AS VARCHAR(3)) AS "CYCLE_OPTION"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."SQL_FEATURES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "FEATURE_ID",
    CAST(NULL AS VARCHAR(2000000)) AS "FEATURE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "SUB_FEATURE_ID",
    CAST(NULL AS VARCHAR(2000000)) AS "SUB_FEATURE_NAME",
    CAST(NULL AS VARCHAR(3)) AS "IS_SUPPORTED",
    CAST(NULL AS VARCHAR(2000000)) AS "IS_VERIFIED_BY",
    CAST(NULL AS VARCHAR(2000000)) AS "COMMENTS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."SQL_IMPLEMENTATION_INFO" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "IMPLEMENTATION_INFO_ID",
    CAST(NULL AS VARCHAR(2000000)) AS "IMPLEMENTATION_INFO_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "INTEGER_VALUE",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_VALUE",
    CAST(NULL AS VARCHAR(2000000)) AS "COMMENTS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."SQL_PARTS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "FEATURE_ID",
    CAST(NULL AS VARCHAR(2000000)) AS "FEATURE_NAME",
    CAST(NULL AS VARCHAR(3)) AS "IS_SUPPORTED",
    CAST(NULL AS VARCHAR(2000000)) AS "IS_VERIFIED_BY",
    CAST(NULL AS VARCHAR(2000000)) AS "COMMENTS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."SQL_SIZING" AS
SELECT
    CAST(NULL AS DECIMAL(36,0)) AS "SIZING_ID",
    CAST(NULL AS VARCHAR(2000000)) AS "SIZING_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "SUPPORTED_VALUE",
    CAST(NULL AS VARCHAR(2000000)) AS "COMMENTS"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."TRANSFORMS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "GROUP_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "TRANSFORM_TYPE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."TRIGGERED_UPDATE_COLUMNS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "TRIGGER_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "TRIGGER_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "TRIGGER_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "EVENT_OBJECT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "EVENT_OBJECT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "EVENT_OBJECT_TABLE",
    CAST(NULL AS VARCHAR(2000000)) AS "EVENT_OBJECT_COLUMN"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."UDT_PRIVILEGES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTOR",
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTEE",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "UDT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "PRIVILEGE_TYPE",
    CAST(NULL AS VARCHAR(3)) AS "IS_GRANTABLE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."USAGE_PRIVILEGES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTOR",
    CAST(NULL AS VARCHAR(2000000)) AS "GRANTEE",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OBJECT_TYPE",
    CAST(NULL AS VARCHAR(2000000)) AS "PRIVILEGE_TYPE",
    CAST(NULL AS VARCHAR(3)) AS "IS_GRANTABLE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."USER_DEFINED_TYPES" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "USER_DEFINED_TYPE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "USER_DEFINED_TYPE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "USER_DEFINED_TYPE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "USER_DEFINED_TYPE_CATEGORY",
    CAST(NULL AS VARCHAR(3)) AS "IS_INSTANTIABLE",
    CAST(NULL AS VARCHAR(3)) AS "IS_FINAL",
    CAST(NULL AS VARCHAR(2000000)) AS "ORDERING_FORM",
    CAST(NULL AS VARCHAR(2000000)) AS "ORDERING_CATEGORY",
    CAST(NULL AS VARCHAR(2000000)) AS "ORDERING_ROUTINE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "ORDERING_ROUTINE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "ORDERING_ROUTINE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "REFERENCE_TYPE",
    CAST(NULL AS VARCHAR(2000000)) AS "DATA_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "CHARACTER_MAXIMUM_LENGTH",
    CAST(NULL AS DECIMAL(36,0)) AS "CHARACTER_OCTET_LENGTH",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "CHARACTER_SET_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "COLLATION_NAME",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_PRECISION_RADIX",
    CAST(NULL AS DECIMAL(36,0)) AS "NUMERIC_SCALE",
    CAST(NULL AS DECIMAL(36,0)) AS "DATETIME_PRECISION",
    CAST(NULL AS VARCHAR(2000000)) AS "INTERVAL_TYPE",
    CAST(NULL AS DECIMAL(36,0)) AS "INTERVAL_PRECISION",
    CAST(NULL AS VARCHAR(2000000)) AS "SOURCE_DTD_IDENTIFIER",
    CAST(NULL AS VARCHAR(2000000)) AS "REF_DTD_IDENTIFIER"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."USER_MAPPING_OPTIONS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "AUTHORIZATION_IDENTIFIER",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OPTION_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "OPTION_VALUE"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."USER_MAPPINGS" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "AUTHORIZATION_IDENTIFIER",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "FOREIGN_SERVER_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."VIEW_COLUMN_USAGE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "VIEW_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "VIEW_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "VIEW_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "COLUMN_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA."VIEW_ROUTINE_USAGE" AS
SELECT
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "TABLE_NAME",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_CATALOG",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_SCHEMA",
    CAST(NULL AS VARCHAR(2000000)) AS "SPECIFIC_NAME"
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;
-- GENERATED_PLACEHOLDER_VIEWS_END
