-- PostgreSQL catalog compatibility layer for Exasol.
--
-- This script creates two schemas, PG_CATALOG and INFORMATION_SCHEMA, and
-- populates them with Exasol-backed compatibility views for the core metadata
-- surfaces used by PostgreSQL clients. PostgreSQL-specific features that do
-- not have an Exasol equivalent are exposed as empty views with the expected
-- columns so clients receive empty result sets instead of object-not-found
-- errors.

CREATE SCHEMA IF NOT EXISTS PG_CATALOG;
CREATE SCHEMA IF NOT EXISTS INFORMATION_SCHEMA;

CREATE OR REPLACE FUNCTION PG_CATALOG.OBJ_DESCRIPTION(
    OBJ_OID DECIMAL(18,0),
    CATALOG_NAME VARCHAR(128)
)
RETURN VARCHAR(2000)
IS
BEGIN
    RETURN NULL;
END OBJ_DESCRIPTION;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_GET_USERBYID(
    USER_OID DECIMAL(18,0)
)
RETURN VARCHAR(128)
IS
BEGIN
    RETURN CASE
        WHEN USER_OID = 10 THEN 'SYS'
        ELSE 'UNKNOWN'
    END;
END PG_GET_USERBYID;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_GET_EXPR(
    EXPR_TEXT VARCHAR(2000),
    REL_OID DECIMAL(18,0)
)
RETURN VARCHAR(2000)
IS
BEGIN
    RETURN EXPR_TEXT;
END PG_GET_EXPR;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_GET_CONSTRAINTDEF(
    CONSTRAINT_OID DECIMAL(18,0)
)
RETURN VARCHAR(2000)
IS
BEGIN
    RETURN NULL;
END PG_GET_CONSTRAINTDEF;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_GET_INDEXDEF(
    INDEX_OID DECIMAL(18,0)
)
RETURN VARCHAR(2000000)
IS
BEGIN
    RETURN NULL;
END PG_GET_INDEXDEF;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_STAT_GET_BLOCKS_FETCHED(
    REL_OID DECIMAL(18,0)
)
RETURN DECIMAL(18,0)
IS
BEGIN
    RETURN 0;
END PG_STAT_GET_BLOCKS_FETCHED;
/

CREATE OR REPLACE FUNCTION PG_CATALOG.PG_STAT_GET_BLOCKS_HIT(
    REL_OID DECIMAL(18,0)
)
RETURN DECIMAL(18,0)
IS
BEGIN
    RETURN 0;
END PG_STAT_GET_BLOCKS_HIT;
/

CREATE OR REPLACE VIEW PG_CATALOG.PG_DATABASE AS
SELECT
    CAST(1 AS DECIMAL(18,0)) AS OID,
    'exasol' AS DATNAME,
    CAST(10 AS DECIMAL(18,0)) AS DATDBA,
    CAST(6 AS DECIMAL(9,0)) AS ENCODING,
    'c' AS DATLOCPROVIDER,
    FALSE AS DATISTEMPLATE,
    TRUE AS DATALLOWCONN,
    FALSE AS DATHASLOGINEVT,
    CAST(-1 AS DECIMAL(9,0)) AS DATCONNLIMIT,
    CAST(0 AS DECIMAL(18,0)) AS DATFROZENXID,
    CAST(0 AS DECIMAL(18,0)) AS DATMINMXID,
    CAST(1663 AS DECIMAL(18,0)) AS DATTABLESPACE,
    'C.UTF-8' AS DATCOLLATE,
    'C.UTF-8' AS DATCTYPE,
    CAST(NULL AS VARCHAR(2000)) AS DATLOCALE,
    CAST(NULL AS VARCHAR(2000)) AS DATICURULES,
    CAST(NULL AS VARCHAR(2000)) AS DATCOLLVERSION,
    CAST(NULL AS VARCHAR(2000)) AS DATACL;

CREATE OR REPLACE VIEW PG_CATALOG.PG_USER AS
SELECT
    USER_NAME AS USENAME,
    CASE WHEN USER_NAME = 'SYS' THEN CAST(10 AS DECIMAL(18,0))
         ELSE CAST(10000 + ROW_NUMBER() OVER (ORDER BY USER_NAME) AS DECIMAL(18,0))
    END AS USESYSID,
    TRUE AS USECREATEDB,
    CASE WHEN USER_NAME = 'SYS' THEN TRUE ELSE FALSE END AS USESUPER,
    FALSE AS USEREPL,
    CASE WHEN USER_NAME = 'SYS' THEN TRUE ELSE FALSE END AS USEBYPASSRLS,
    CAST(NULL AS VARCHAR(64)) AS PASSWD,
    PASSWORD_EXPIRY AS VALUNTIL,
    CAST(NULL AS VARCHAR(2000)) AS USECONFIG
FROM SYS.EXA_DBA_USERS;

CREATE OR REPLACE VIEW PG_CATALOG.PG_GROUP AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS GRONAME,
    CAST(NULL AS DECIMAL(18,0)) AS GROSYSID,
    CAST(NULL AS VARCHAR(2000)) AS GROLIST
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_ROLES AS
WITH ROLE_BASE AS (
    SELECT
        USER_NAME AS ROLE_NAME,
        TRUE AS CAN_LOGIN,
        CASE WHEN USER_NAME = 'SYS' THEN CAST(10 AS DECIMAL(18,0))
             ELSE CAST(10000 + ROW_NUMBER() OVER (ORDER BY USER_NAME) AS DECIMAL(18,0))
        END AS ROLE_OID,
        USER_COMMENT AS ROLE_COMMENT
    FROM SYS.EXA_DBA_USERS
    UNION ALL
    SELECT
        ROLE_NAME,
        FALSE AS CAN_LOGIN,
        CAST(20000 + ROW_NUMBER() OVER (ORDER BY ROLE_NAME) AS DECIMAL(18,0)) AS ROLE_OID,
        ROLE_COMMENT
    FROM SYS.EXA_DBA_ROLES
)
SELECT
    ROLE_OID AS OID,
    ROLE_NAME AS ROLNAME,
    CASE WHEN ROLE_NAME = 'SYS' THEN TRUE ELSE FALSE END AS ROLSUPER,
    TRUE AS ROLINHERIT,
    CASE WHEN ROLE_NAME = 'SYS' THEN TRUE ELSE FALSE END AS ROLCREATEROLE,
    CASE WHEN ROLE_NAME = 'SYS' THEN TRUE ELSE FALSE END AS ROLCREATEDB,
    CAN_LOGIN AS ROLCANLOGIN,
    FALSE AS ROLREPLICATION,
    CAST(-1 AS DECIMAL(9,0)) AS ROLCONNLIMIT,
    CAST(NULL AS VARCHAR(64)) AS ROLPASSWORD,
    CAST(NULL AS TIMESTAMP) AS ROLVALIDUNTIL,
    CASE WHEN ROLE_NAME = 'SYS' THEN TRUE ELSE FALSE END AS ROLBYPASSRLS,
    CAST(NULL AS VARCHAR(2000)) AS ROLCONFIG,
    ROLE_COMMENT AS ROLCOMMENT
FROM ROLE_BASE;

CREATE OR REPLACE VIEW PG_CATALOG.PG_SETTINGS AS
SELECT
    'server_version' AS "NAME",
    '16.6-exasol-gateway' AS "SETTING",
    CAST(NULL AS VARCHAR(64)) AS "UNIT",
    'internal' AS "CONTEXT",
    'string' AS "VARTYPE",
    'default' AS "SOURCE",
    CAST(NULL AS VARCHAR(128)) AS "MIN_VAL",
    CAST(NULL AS VARCHAR(128)) AS "MAX_VAL",
    CAST(NULL AS VARCHAR(2000)) AS "ENUMVALS",
    '16.6-exasol-gateway' AS "BOOT_VAL",
    '16.6-exasol-gateway' AS "RESET_VAL",
    CAST(NULL AS VARCHAR(2000)) AS "SOURCEFILE",
    CAST(NULL AS DECIMAL(18,0)) AS "SOURCELINE",
    FALSE AS "PENDING_RESTART"
UNION ALL
SELECT
    'client_encoding',
    'UTF8',
    CAST(NULL AS VARCHAR(64)),
    'user',
    'string',
    'client',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    'UTF8',
    'UTF8',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE
UNION ALL
SELECT
    'standard_conforming_strings',
    'on',
    CAST(NULL AS VARCHAR(64)),
    'user',
    'bool',
    'default',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    'on',
    'on',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE
UNION ALL
SELECT
    'TimeZone',
    'Etc/UTC',
    CAST(NULL AS VARCHAR(64)),
    'user',
    'string',
    'default',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(2000)),
    'Etc/UTC',
    'Etc/UTC',
    CAST(NULL AS VARCHAR(2000)),
    CAST(NULL AS DECIMAL(18,0)),
    FALSE;

CREATE OR REPLACE VIEW PG_CATALOG.PG_NAMESPACE AS
WITH ROLE_LOOKUP AS (
    SELECT OID, ROLNAME
    FROM PG_CATALOG.PG_ROLES
)
SELECT
    SCHEMA_OBJECT_ID AS OID,
    SCHEMA_NAME AS NSPNAME,
    COALESCE(R.OID, CAST(10 AS DECIMAL(18,0))) AS NSPOWNER,
    CAST(NULL AS VARCHAR(2000)) AS NSPACL
FROM SYS.EXA_DBA_SCHEMAS
LEFT JOIN ROLE_LOOKUP R
  ON R.ROLNAME = SCHEMA_OWNER
WHERE SCHEMA_NAME NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA')
UNION ALL
SELECT CAST(11 AS DECIMAL(18,0)), 'PG_CATALOG', CAST(10 AS DECIMAL(18,0)), CAST(NULL AS VARCHAR(2000))
UNION ALL
SELECT CAST(12 AS DECIMAL(18,0)), 'INFORMATION_SCHEMA', CAST(10 AS DECIMAL(18,0)), CAST(NULL AS VARCHAR(2000));

CREATE OR REPLACE VIEW PG_CATALOG.PG_TABLESPACE AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS OID,
    CAST(NULL AS VARCHAR(128)) AS SPCNAME,
    CAST(NULL AS DECIMAL(18,0)) AS SPCOWNER,
    CAST(NULL AS VARCHAR(2000)) AS SPCACL,
    CAST(NULL AS VARCHAR(2000)) AS SPCOPTIONS
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_TYPE AS
SELECT CAST(16 AS DECIMAL(18,0)) AS OID, 'bool' AS TYPNAME, CAST(11 AS DECIMAL(18,0)) AS TYPNAMESPACE, CAST(10 AS DECIMAL(18,0)) AS TYPOWNER, CAST(1 AS DECIMAL(9,0)) AS TYPLEN, FALSE AS TYPBYVAL, 'b' AS TYPTYPE, FALSE AS TYPNOTNULL, CAST(-1 AS DECIMAL(18,0)) AS TYPTYPMOD, CAST(0 AS DECIMAL(18,0)) AS TYPBASETYPE
UNION ALL
SELECT CAST(25 AS DECIMAL(18,0)), 'text', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1042 AS DECIMAL(18,0)), 'bpchar', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1043 AS DECIMAL(18,0)), 'varchar', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1082 AS DECIMAL(18,0)), 'date', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(4 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1114 AS DECIMAL(18,0)), 'timestamp', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(8 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1184 AS DECIMAL(18,0)), 'timestamptz', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(8 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(700 AS DECIMAL(18,0)), 'float4', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(4 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(701 AS DECIMAL(18,0)), 'float8', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(8 AS DECIMAL(9,0)), TRUE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0))
UNION ALL
SELECT CAST(1700 AS DECIMAL(18,0)), 'numeric', CAST(11 AS DECIMAL(18,0)), CAST(10 AS DECIMAL(18,0)), CAST(-1 AS DECIMAL(9,0)), FALSE, 'b', FALSE, CAST(-1 AS DECIMAL(18,0)), CAST(0 AS DECIMAL(18,0));

CREATE OR REPLACE VIEW PG_CATALOG.PG_CLASS AS
WITH TABLE_COLUMNS AS (
    SELECT COLUMN_SCHEMA, COLUMN_TABLE, COUNT(*) AS COLUMN_COUNT
    FROM SYS.EXA_DBA_COLUMNS
    WHERE COLUMN_OBJECT_TYPE = 'TABLE'
    GROUP BY COLUMN_SCHEMA, COLUMN_TABLE
),
VIEW_COLUMNS AS (
    SELECT COLUMN_SCHEMA, COLUMN_TABLE, COUNT(*) AS COLUMN_COUNT
    FROM SYS.EXA_DBA_COLUMNS
    WHERE COLUMN_OBJECT_TYPE = 'VIEW'
    GROUP BY COLUMN_SCHEMA, COLUMN_TABLE
),
TABLE_INDEXES AS (
    SELECT INDEX_SCHEMA, INDEX_TABLE, COUNT(*) AS INDEX_COUNT
    FROM SYS.EXA_DBA_INDICES
    GROUP BY INDEX_SCHEMA, INDEX_TABLE
),
ROLE_LOOKUP AS (
    SELECT OID, ROLNAME
    FROM PG_CATALOG.PG_ROLES
)
SELECT
    T.TABLE_OBJECT_ID AS OID,
    T.TABLE_NAME AS RELNAME,
    N.OID AS RELNAMESPACE,
    CAST(0 AS DECIMAL(18,0)) AS RELTYPE,
    CAST(0 AS DECIMAL(18,0)) AS RELOFTYPE,
    COALESCE(R.OID, CAST(10 AS DECIMAL(18,0))) AS RELOWNER,
    CAST(0 AS DECIMAL(18,0)) AS RELAM,
    CAST(0 AS DECIMAL(18,0)) AS RELFILENODE,
    CAST(0 AS DECIMAL(18,0)) AS RELTABLESPACE,
    CAST(0 AS DECIMAL(18,0)) AS RELPAGES,
    COALESCE(T.TABLE_ROW_COUNT, 0) AS RELTUPLES,
    CAST(0 AS DECIMAL(18,0)) AS RELALLVISIBLE,
    CAST(0 AS DECIMAL(18,0)) AS RELTOASTRELID,
    COALESCE(I.INDEX_COUNT, 0) > 0 AS RELHASINDEX,
    FALSE AS RELISSHARED,
    'p' AS RELPERSISTENCE,
    'r' AS RELKIND,
    COALESCE(C.COLUMN_COUNT, 0) AS RELNATTS,
    CAST(0 AS DECIMAL(18,0)) AS RELCHECKS,
    FALSE AS RELHASRULES,
    FALSE AS RELHASTRIGGERS,
    FALSE AS RELHASSUBCLASS,
    FALSE AS RELROWSECURITY,
    FALSE AS RELFORCEROWSECURITY,
    TRUE AS RELISPOPULATED,
    'n' AS RELREPLIDENT,
    FALSE AS RELISPARTITION,
    CAST(0 AS DECIMAL(18,0)) AS RELREWRITE,
    CAST(0 AS DECIMAL(18,0)) AS RELFROZENXID,
    CAST(0 AS DECIMAL(18,0)) AS RELMINMXID,
    CAST(NULL AS VARCHAR(2000)) AS RELACL,
    CAST(NULL AS VARCHAR(2000)) AS RELOPTIONS,
    CAST(NULL AS VARCHAR(2000)) AS RELPARTBOUND
FROM SYS.EXA_DBA_TABLES T
JOIN PG_CATALOG.PG_NAMESPACE N
  ON N.NSPNAME = T.TABLE_SCHEMA
LEFT JOIN ROLE_LOOKUP R
  ON R.ROLNAME = T.TABLE_OWNER
LEFT JOIN TABLE_COLUMNS C
  ON C.COLUMN_SCHEMA = T.TABLE_SCHEMA AND C.COLUMN_TABLE = T.TABLE_NAME
LEFT JOIN TABLE_INDEXES I
  ON I.INDEX_SCHEMA = T.TABLE_SCHEMA AND I.INDEX_TABLE = T.TABLE_NAME
WHERE T.TABLE_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA')
UNION ALL
SELECT
    V.VIEW_OBJECT_ID AS OID,
    V.VIEW_NAME AS RELNAME,
    N.OID AS RELNAMESPACE,
    CAST(0 AS DECIMAL(18,0)) AS RELTYPE,
    CAST(0 AS DECIMAL(18,0)) AS RELOFTYPE,
    COALESCE(R.OID, CAST(10 AS DECIMAL(18,0))) AS RELOWNER,
    CAST(0 AS DECIMAL(18,0)) AS RELAM,
    CAST(0 AS DECIMAL(18,0)) AS RELFILENODE,
    CAST(0 AS DECIMAL(18,0)) AS RELTABLESPACE,
    CAST(0 AS DECIMAL(18,0)) AS RELPAGES,
    CAST(0 AS DECIMAL(18,0)) AS RELTUPLES,
    CAST(0 AS DECIMAL(18,0)) AS RELALLVISIBLE,
    CAST(0 AS DECIMAL(18,0)) AS RELTOASTRELID,
    FALSE AS RELHASINDEX,
    FALSE AS RELISSHARED,
    'p' AS RELPERSISTENCE,
    'v' AS RELKIND,
    COALESCE(C.COLUMN_COUNT, 0) AS RELNATTS,
    CAST(0 AS DECIMAL(18,0)) AS RELCHECKS,
    FALSE AS RELHASRULES,
    FALSE AS RELHASTRIGGERS,
    FALSE AS RELHASSUBCLASS,
    FALSE AS RELROWSECURITY,
    FALSE AS RELFORCEROWSECURITY,
    TRUE AS RELISPOPULATED,
    'n' AS RELREPLIDENT,
    FALSE AS RELISPARTITION,
    CAST(0 AS DECIMAL(18,0)) AS RELREWRITE,
    CAST(0 AS DECIMAL(18,0)) AS RELFROZENXID,
    CAST(0 AS DECIMAL(18,0)) AS RELMINMXID,
    CAST(NULL AS VARCHAR(2000)) AS RELACL,
    CAST(NULL AS VARCHAR(2000)) AS RELOPTIONS,
    CAST(NULL AS VARCHAR(2000)) AS RELPARTBOUND
FROM SYS.EXA_DBA_VIEWS V
JOIN PG_CATALOG.PG_NAMESPACE N
  ON N.NSPNAME = V.VIEW_SCHEMA
LEFT JOIN ROLE_LOOKUP R
  ON R.ROLNAME = V.VIEW_OWNER
LEFT JOIN VIEW_COLUMNS C
  ON C.COLUMN_SCHEMA = V.VIEW_SCHEMA AND C.COLUMN_TABLE = V.VIEW_NAME
WHERE V.VIEW_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW PG_CATALOG.PG_ATTRIBUTE AS
SELECT
    CLS.OID AS ATTRELID,
    COL.COLUMN_NAME AS ATTNAME,
    CASE
        WHEN COL.COLUMN_TYPE LIKE 'DECIMAL(%' THEN CAST(1700 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE LIKE 'VARCHAR(%' THEN CAST(1043 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE LIKE 'CHAR(%' THEN CAST(1042 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE LIKE 'TIMESTAMP%' THEN CAST(1114 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE = 'DATE' THEN CAST(1082 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE = 'BOOLEAN' THEN CAST(16 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE IN ('DOUBLE', 'DOUBLE PRECISION') THEN CAST(701 AS DECIMAL(18,0))
        WHEN COL.COLUMN_TYPE = 'REAL' THEN CAST(700 AS DECIMAL(18,0))
        ELSE CAST(25 AS DECIMAL(18,0))
    END AS ATTTYPID,
    CASE
        WHEN COL.COLUMN_TYPE LIKE 'TIMESTAMP%' THEN CAST(8 AS DECIMAL(9,0))
        WHEN COL.COLUMN_TYPE = 'DATE' THEN CAST(4 AS DECIMAL(9,0))
        WHEN COL.COLUMN_TYPE = 'BOOLEAN' THEN CAST(1 AS DECIMAL(9,0))
        WHEN COL.COLUMN_TYPE = 'REAL' THEN CAST(4 AS DECIMAL(9,0))
        WHEN COL.COLUMN_TYPE IN ('DOUBLE', 'DOUBLE PRECISION') THEN CAST(8 AS DECIMAL(9,0))
        ELSE CAST(-1 AS DECIMAL(9,0))
    END AS ATTLEN,
    COL.COLUMN_ORDINAL_POSITION AS ATTNUM,
    CASE
        WHEN COL.COLUMN_TYPE LIKE 'DECIMAL(%' THEN (COALESCE(COL.COLUMN_NUM_PREC, 36) * 65536) + COALESCE(COL.COLUMN_NUM_SCALE, 0) + 4
        WHEN COL.COLUMN_TYPE LIKE 'VARCHAR(%' THEN COALESCE(COL.COLUMN_MAXSIZE, 0) + 4
        WHEN COL.COLUMN_TYPE LIKE 'CHAR(%' THEN COALESCE(COL.COLUMN_MAXSIZE, 0) + 4
        WHEN COL.COLUMN_TYPE LIKE 'TIMESTAMP%' THEN 10
        ELSE -1
    END AS ATTTYPMOD,
    CAST(0 AS DECIMAL(9,0)) AS ATTNDIMS,
    FALSE AS ATTBYVAL,
    COALESCE(COL.COLUMN_IS_NULLABLE = FALSE, FALSE) AS ATTNOTNULL,
    CAST(NULL AS VARCHAR(1)) AS ATTIDENTITY,
    CAST(NULL AS VARCHAR(1)) AS ATTGENERATED,
    FALSE AS ATTISDROPPED
FROM SYS.EXA_DBA_COLUMNS COL
JOIN PG_CATALOG.PG_NAMESPACE NS
  ON NS.NSPNAME = COL.COLUMN_SCHEMA
JOIN PG_CATALOG.PG_CLASS CLS
  ON CLS.RELNAME = COL.COLUMN_TABLE
 AND CLS.RELNAMESPACE = NS.OID
WHERE COL.COLUMN_OBJECT_TYPE IN ('TABLE', 'VIEW');

CREATE OR REPLACE VIEW PG_CATALOG.PG_ATTRDEF AS
SELECT
    CAST((CLS.OID * 1000) + COL.COLUMN_ORDINAL_POSITION AS DECIMAL(18,0)) AS OID,
    CLS.OID AS ADRELID,
    COL.COLUMN_ORDINAL_POSITION AS ADNUM,
    COL.COLUMN_DEFAULT AS ADBIN
FROM SYS.EXA_DBA_COLUMNS COL
JOIN PG_CATALOG.PG_NAMESPACE NS
  ON NS.NSPNAME = COL.COLUMN_SCHEMA
JOIN PG_CATALOG.PG_CLASS CLS
  ON CLS.RELNAME = COL.COLUMN_TABLE
 AND CLS.RELNAMESPACE = NS.OID
WHERE COL.COLUMN_DEFAULT IS NOT NULL
  AND COL.COLUMN_OBJECT_TYPE IN ('TABLE', 'VIEW');

CREATE OR REPLACE VIEW PG_CATALOG.PG_DESCRIPTION AS
SELECT
    NS.OID AS OBJOID,
    CAST(2615 AS DECIMAL(18,0)) AS CLASSOID,
    CAST(0 AS DECIMAL(18,0)) AS OBJSUBID,
    S.SCHEMA_COMMENT AS DESCRIPTION
FROM SYS.EXA_DBA_SCHEMAS S
JOIN PG_CATALOG.PG_NAMESPACE NS
  ON NS.NSPNAME = S.SCHEMA_NAME
WHERE S.SCHEMA_COMMENT IS NOT NULL
UNION ALL
SELECT
    CLS.OID AS OBJOID,
    CAST(1259 AS DECIMAL(18,0)) AS CLASSOID,
    CAST(0 AS DECIMAL(18,0)) AS OBJSUBID,
    OBJ.OBJECT_COMMENT AS DESCRIPTION
FROM SYS.EXA_DBA_OBJECTS OBJ
JOIN PG_CATALOG.PG_CLASS CLS
  ON CLS.OID = OBJ.OBJECT_ID
WHERE OBJ.OBJECT_COMMENT IS NOT NULL
UNION ALL
SELECT
    CLS.OID AS OBJOID,
    CAST(1259 AS DECIMAL(18,0)) AS CLASSOID,
    COL.COLUMN_ORDINAL_POSITION AS OBJSUBID,
    COL.COLUMN_COMMENT AS DESCRIPTION
FROM SYS.EXA_DBA_COLUMNS COL
JOIN PG_CATALOG.PG_NAMESPACE NS
  ON NS.NSPNAME = COL.COLUMN_SCHEMA
JOIN PG_CATALOG.PG_CLASS CLS
  ON CLS.RELNAME = COL.COLUMN_TABLE
 AND CLS.RELNAMESPACE = NS.OID
WHERE COL.COLUMN_COMMENT IS NOT NULL
  AND COL.COLUMN_OBJECT_TYPE IN ('TABLE', 'VIEW');

CREATE OR REPLACE VIEW PG_CATALOG.PG_INDEX AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS INDEXRELID,
    CAST(NULL AS DECIMAL(18,0)) AS INDRELID,
    CAST(NULL AS DECIMAL(9,0)) AS INDNATTS,
    CAST(NULL AS DECIMAL(9,0)) AS INDNKEYATTS,
    CAST(NULL AS BOOLEAN) AS INDISUNIQUE,
    CAST(NULL AS BOOLEAN) AS INDNULLSNOTDISTINCT,
    CAST(NULL AS BOOLEAN) AS INDISPRIMARY,
    CAST(NULL AS BOOLEAN) AS INDISEXCLUSION,
    CAST(NULL AS BOOLEAN) AS INDISIMMEDIATE,
    CAST(NULL AS BOOLEAN) AS INDISCLUSTERED
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_CONSTRAINT AS
WITH REF_TARGET AS (
    SELECT
        CONSTRAINT_SCHEMA,
        CONSTRAINT_TABLE,
        CONSTRAINT_NAME,
        MAX(REFERENCED_SCHEMA) AS REFERENCED_SCHEMA,
        MAX(REFERENCED_TABLE) AS REFERENCED_TABLE
    FROM SYS.EXA_DBA_CONSTRAINT_COLUMNS
    GROUP BY CONSTRAINT_SCHEMA, CONSTRAINT_TABLE, CONSTRAINT_NAME
)
SELECT
    CAST(500000 + ROW_NUMBER() OVER (ORDER BY C.CONSTRAINT_SCHEMA, C.CONSTRAINT_TABLE, C.CONSTRAINT_NAME) AS DECIMAL(18,0)) AS OID,
    C.CONSTRAINT_NAME AS CONNAME,
    NS.OID AS CONNAMESPACE,
    CASE
        WHEN C.CONSTRAINT_TYPE = 'PRIMARY KEY' THEN 'p'
        WHEN C.CONSTRAINT_TYPE = 'FOREIGN KEY' THEN 'f'
        WHEN C.CONSTRAINT_TYPE = 'NOT NULL' THEN 'n'
        ELSE 'c'
    END AS CONTYPE,
    FALSE AS CONDEFERRABLE,
    FALSE AS CONDEFERRED,
    TRUE AS CONVALIDATED,
    CLS.OID AS CONRELID,
    CAST(0 AS DECIMAL(18,0)) AS CONTYPID,
    CAST(0 AS DECIMAL(18,0)) AS CONINDID,
    CAST(0 AS DECIMAL(18,0)) AS CONPARENTID,
    CAST(CASE WHEN C.CONSTRAINT_TYPE = 'FOREIGN KEY' THEN REFCLS.OID ELSE 0 END AS DECIMAL(18,0)) AS CONFRELID,
    CAST(NULL AS VARCHAR(2000)) AS CONKEY,
    CAST(NULL AS VARCHAR(2000)) AS CONFKEY,
    CAST(NULL AS VARCHAR(2000)) AS CONBIN
FROM SYS.EXA_DBA_CONSTRAINTS C
JOIN PG_CATALOG.PG_NAMESPACE NS
  ON NS.NSPNAME = C.CONSTRAINT_SCHEMA
JOIN PG_CATALOG.PG_CLASS CLS
  ON CLS.RELNAME = C.CONSTRAINT_TABLE
 AND CLS.RELNAMESPACE = NS.OID
LEFT JOIN REF_TARGET RT
  ON RT.CONSTRAINT_SCHEMA = C.CONSTRAINT_SCHEMA
 AND RT.CONSTRAINT_TABLE = C.CONSTRAINT_TABLE
 AND RT.CONSTRAINT_NAME = C.CONSTRAINT_NAME
LEFT JOIN PG_CATALOG.PG_NAMESPACE RNS
  ON RNS.NSPNAME = RT.REFERENCED_SCHEMA
LEFT JOIN PG_CATALOG.PG_CLASS REFCLS
  ON REFCLS.RELNAME = RT.REFERENCED_TABLE
 AND REFCLS.RELNAMESPACE = RNS.OID
WHERE C.CONSTRAINT_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW PG_CATALOG.PG_TABLES AS
SELECT
    TABLE_SCHEMA AS SCHEMANAME,
    TABLE_NAME AS TABLENAME,
    TABLE_OWNER AS TABLEOWNER,
    CAST(NULL AS VARCHAR(128)) AS TABLESPACE,
    FALSE AS HASINDEXES,
    FALSE AS HASRULES,
    FALSE AS HASTRIGGERS,
    FALSE AS ROWSECURITY
FROM SYS.EXA_DBA_TABLES
WHERE TABLE_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW PG_CATALOG.PG_VIEWS AS
SELECT
    VIEW_SCHEMA AS SCHEMANAME,
    VIEW_NAME AS VIEWNAME,
    VIEW_OWNER AS VIEWOWNER,
    VIEW_TEXT AS DEFINITION
FROM SYS.EXA_DBA_VIEWS
WHERE VIEW_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW PG_CATALOG.PG_MATVIEWS AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS SCHEMANAME,
    CAST(NULL AS VARCHAR(128)) AS MATVIEWNAME,
    CAST(NULL AS VARCHAR(128)) AS MATVIEWOWNER,
    CAST(NULL AS VARCHAR(128)) AS TABLESPACE,
    CAST(NULL AS BOOLEAN) AS HASINDEXES,
    CAST(NULL AS BOOLEAN) AS ISPOPULATED,
    CAST(NULL AS VARCHAR(2000000)) AS DEFINITION
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_LOCKS AS
SELECT
    CAST(NULL AS VARCHAR(32)) AS LOCKTYPE,
    CAST(NULL AS DECIMAL(18,0)) AS DATABASE,
    CAST(NULL AS DECIMAL(18,0)) AS RELATION,
    CAST(NULL AS DECIMAL(18,0)) AS PAGE,
    CAST(NULL AS DECIMAL(18,0)) AS TUPLE,
    CAST(NULL AS VARCHAR(64)) AS VIRTUALXID,
    CAST(NULL AS DECIMAL(18,0)) AS TRANSACTIONID,
    CAST(NULL AS DECIMAL(18,0)) AS CLASSID,
    CAST(NULL AS DECIMAL(18,0)) AS OBJID,
    CAST(NULL AS DECIMAL(18,0)) AS OBJSUBID,
    CAST(NULL AS VARCHAR(64)) AS VIRTUALTRANSACTION,
    CAST(NULL AS DECIMAL(18,0)) AS PID,
    CAST(NULL AS VARCHAR(64)) AS MODE,
    CAST(NULL AS BOOLEAN) AS "GRANTED",
    CAST(NULL AS BOOLEAN) AS FASTPATH,
    CAST(NULL AS TIMESTAMP) AS WAITSTART
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_STAT_ACTIVITY AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS DATID,
    CAST(NULL AS VARCHAR(128)) AS DATNAME,
    CAST(NULL AS DECIMAL(18,0)) AS PID,
    CAST(NULL AS DECIMAL(18,0)) AS LEADER_PID,
    CAST(NULL AS DECIMAL(18,0)) AS USESYSID,
    CAST(NULL AS VARCHAR(128)) AS USENAME,
    CAST(NULL AS VARCHAR(128)) AS APPLICATION_NAME,
    CAST(NULL AS VARCHAR(128)) AS CLIENT_ADDR,
    CAST(NULL AS VARCHAR(128)) AS CLIENT_HOSTNAME,
    CAST(NULL AS DECIMAL(18,0)) AS CLIENT_PORT,
    CAST(NULL AS TIMESTAMP) AS BACKEND_START,
    CAST(NULL AS TIMESTAMP) AS XACT_START,
    CAST(NULL AS TIMESTAMP) AS QUERY_START,
    CAST(NULL AS TIMESTAMP) AS STATE_CHANGE,
    CAST(NULL AS VARCHAR(64)) AS WAIT_EVENT_TYPE,
    CAST(NULL AS VARCHAR(128)) AS WAIT_EVENT,
    CAST(NULL AS VARCHAR(64)) AS "STATE",
    CAST(NULL AS DECIMAL(18,0)) AS BACKEND_XID,
    CAST(NULL AS DECIMAL(18,0)) AS BACKEND_XMIN,
    CAST(NULL AS DECIMAL(18,0)) AS QUERY_ID,
    CAST(NULL AS VARCHAR(2000000)) AS "QUERY",
    CAST(NULL AS VARCHAR(128)) AS BACKEND_TYPE
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_REWRITE AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS RULENAME,
    CAST(NULL AS DECIMAL(18,0)) AS EV_CLASS,
    CAST(NULL AS VARCHAR(1)) AS EV_TYPE,
    CAST(NULL AS DECIMAL(18,0)) AS OID
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_RULES AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS SCHEMANAME,
    CAST(NULL AS VARCHAR(128)) AS TABLENAME,
    CAST(NULL AS VARCHAR(128)) AS RULENAME,
    CAST(NULL AS VARCHAR(2000000)) AS DEFINITION
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_TRIGGER AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS TGNAME,
    CAST(NULL AS DECIMAL(18,0)) AS TGRELID,
    CAST(NULL AS DECIMAL(18,0)) AS TGFOID,
    CAST(NULL AS VARCHAR(1)) AS TGENABLED
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_PROC AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS OID,
    CAST(NULL AS VARCHAR(128)) AS PRONAME,
    CAST(NULL AS VARCHAR(2000)) AS PROARGTYPES
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_FOREIGN_TABLE AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS FTRELID,
    CAST(NULL AS DECIMAL(18,0)) AS FTSERVER,
    CAST(NULL AS VARCHAR(2000)) AS FTOPTIONS
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_FOREIGN_SERVER AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS OID,
    CAST(NULL AS VARCHAR(128)) AS SRVNAME
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_DEPEND AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS CLASSID,
    CAST(NULL AS DECIMAL(18,0)) AS OBJID,
    CAST(NULL AS DECIMAL(18,0)) AS REFOBJID,
    CAST(NULL AS DECIMAL(18,0)) AS REFCLASSID
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW PG_CATALOG.PG_SEQUENCE AS
SELECT
    CAST(NULL AS DECIMAL(18,0)) AS SEQRELID,
    CAST(NULL AS DECIMAL(18,0)) AS SEQINCREMENT,
    CAST(NULL AS DECIMAL(18,0)) AS SEQMAX,
    CAST(NULL AS DECIMAL(18,0)) AS SEQMIN,
    CAST(NULL AS DECIMAL(18,0)) AS SEQCACHE,
    CAST(NULL AS BOOLEAN) AS SEQCYCLE
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.SCHEMATA AS
SELECT
    'exasol' AS CATALOG_NAME,
    NSPNAME AS SCHEMA_NAME,
    'SYS' AS SCHEMA_OWNER,
    CAST(NULL AS VARCHAR(128)) AS DEFAULT_CHARACTER_SET_CATALOG,
    CAST(NULL AS VARCHAR(128)) AS DEFAULT_CHARACTER_SET_SCHEMA,
    CAST(NULL AS VARCHAR(128)) AS DEFAULT_CHARACTER_SET_NAME,
    CAST(NULL AS VARCHAR(2000)) AS SQL_PATH
FROM PG_CATALOG.PG_NAMESPACE;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.TABLES AS
SELECT
    'exasol' AS TABLE_CATALOG,
    TABLE_SCHEMA AS TABLE_SCHEMA,
    TABLE_NAME AS TABLE_NAME,
    'BASE TABLE' AS TABLE_TYPE,
    CAST(NULL AS VARCHAR(128)) AS SELF_REFERENCING_COLUMN_NAME,
    CAST(NULL AS VARCHAR(128)) AS REFERENCE_GENERATION,
    CAST(NULL AS VARCHAR(128)) AS USER_DEFINED_TYPE_CATALOG,
    CAST(NULL AS VARCHAR(128)) AS USER_DEFINED_TYPE_SCHEMA,
    CAST(NULL AS VARCHAR(128)) AS USER_DEFINED_TYPE_NAME,
    'YES' AS IS_INSERTABLE_INTO,
    'NO' AS IS_TYPED,
    CAST(NULL AS VARCHAR(128)) AS COMMIT_ACTION
FROM SYS.EXA_DBA_TABLES
WHERE TABLE_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA')
UNION ALL
SELECT
    'exasol',
    VIEW_SCHEMA,
    VIEW_NAME,
    'VIEW',
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    CAST(NULL AS VARCHAR(128)),
    'NO',
    'NO',
    CAST(NULL AS VARCHAR(128))
FROM SYS.EXA_DBA_VIEWS
WHERE VIEW_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.VIEWS AS
SELECT
    'exasol' AS TABLE_CATALOG,
    VIEW_SCHEMA AS TABLE_SCHEMA,
    VIEW_NAME AS TABLE_NAME,
    VIEW_TEXT AS VIEW_DEFINITION,
    'NONE' AS CHECK_OPTION,
    'NO' AS IS_UPDATABLE,
    'NO' AS IS_INSERTABLE_INTO,
    'NO' AS IS_TRIGGER_UPDATABLE,
    'NO' AS IS_TRIGGER_DELETABLE,
    'NO' AS IS_TRIGGER_INSERTABLE_INTO
FROM SYS.EXA_DBA_VIEWS
WHERE VIEW_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.COLUMNS AS
SELECT
    'exasol' AS "TABLE_CATALOG",
    COLUMN_SCHEMA AS "TABLE_SCHEMA",
    COLUMN_TABLE AS "TABLE_NAME",
    COLUMN_NAME AS "COLUMN_NAME",
    COLUMN_ORDINAL_POSITION AS "ORDINAL_POSITION",
    COLUMN_DEFAULT AS "COLUMN_DEFAULT",
    CASE WHEN COLUMN_IS_NULLABLE THEN 'YES' ELSE 'NO' END AS "IS_NULLABLE",
    CASE
        WHEN COLUMN_TYPE LIKE 'DECIMAL(%' THEN 'numeric'
        WHEN COLUMN_TYPE LIKE 'VARCHAR(%' THEN 'character varying'
        WHEN COLUMN_TYPE LIKE 'CHAR(%' THEN 'character'
        WHEN COLUMN_TYPE LIKE 'TIMESTAMP%' THEN 'timestamp without time zone'
        WHEN COLUMN_TYPE = 'DATE' THEN 'date'
        WHEN COLUMN_TYPE = 'BOOLEAN' THEN 'boolean'
        WHEN COLUMN_TYPE IN ('DOUBLE', 'DOUBLE PRECISION') THEN 'double precision'
        WHEN COLUMN_TYPE = 'REAL' THEN 'real'
        ELSE 'text'
    END AS "DATA_TYPE",
    COLUMN_MAXSIZE AS "CHARACTER_MAXIMUM_LENGTH",
    COLUMN_MAXSIZE AS "CHARACTER_OCTET_LENGTH",
    COLUMN_NUM_PREC AS "NUMERIC_PRECISION",
    COLUMN_NUM_SCALE AS "NUMERIC_SCALE",
    CAST(10 AS DECIMAL(9,0)) AS "NUMERIC_PRECISION_RADIX",
    CAST(NULL AS DECIMAL(9,0)) AS "DATETIME_PRECISION",
    CAST(NULL AS VARCHAR(128)) AS "INTERVAL_TYPE",
    CAST(NULL AS DECIMAL(9,0)) AS "INTERVAL_PRECISION",
    CAST(NULL AS VARCHAR(128)) AS "CHARACTER_SET_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "CHARACTER_SET_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "CHARACTER_SET_NAME",
    CAST(NULL AS VARCHAR(128)) AS "COLLATION_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "COLLATION_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "COLLATION_NAME",
    'exasol' AS "DOMAIN_CATALOG",
    COLUMN_SCHEMA AS "DOMAIN_SCHEMA",
    CASE
        WHEN COLUMN_TYPE LIKE 'DECIMAL(%' THEN 'numeric'
        WHEN COLUMN_TYPE LIKE 'VARCHAR(%' THEN 'varchar'
        WHEN COLUMN_TYPE LIKE 'CHAR(%' THEN 'bpchar'
        WHEN COLUMN_TYPE LIKE 'TIMESTAMP%' THEN 'timestamp'
        WHEN COLUMN_TYPE = 'DATE' THEN 'date'
        WHEN COLUMN_TYPE = 'BOOLEAN' THEN 'bool'
        WHEN COLUMN_TYPE IN ('DOUBLE', 'DOUBLE PRECISION') THEN 'float8'
        WHEN COLUMN_TYPE = 'REAL' THEN 'float4'
        ELSE 'text'
    END AS "UDT_NAME",
    CAST(NULL AS VARCHAR(128)) AS "SCOPE_CATALOG",
    CAST(NULL AS VARCHAR(128)) AS "SCOPE_SCHEMA",
    CAST(NULL AS VARCHAR(128)) AS "SCOPE_NAME",
    CAST(NULL AS DECIMAL(9,0)) AS "MAXIMUM_CARDINALITY",
    CAST(NULL AS VARCHAR(128)) AS "DTD_IDENTIFIER",
    'NO' AS "IS_SELF_REFERENCING",
    'NO' AS "IS_IDENTITY",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_GENERATION",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_START",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_INCREMENT",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_MAXIMUM",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_MINIMUM",
    CAST(NULL AS VARCHAR(128)) AS "IDENTITY_CYCLE",
    'NO' AS "IS_GENERATED",
    CAST(NULL AS VARCHAR(2000)) AS "GENERATION_EXPRESSION",
    CASE WHEN COLUMN_IDENTITY IS NULL THEN 'NO' ELSE 'YES' END AS "IS_UPDATABLE"
FROM SYS.EXA_DBA_COLUMNS
WHERE COLUMN_OBJECT_TYPE IN ('TABLE', 'VIEW')
  AND COLUMN_SCHEMA NOT IN ('SYS', 'PG_CATALOG', 'INFORMATION_SCHEMA');

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS
SELECT
    'exasol' AS CONSTRAINT_CATALOG,
    CONSTRAINT_SCHEMA AS CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS CONSTRAINT_NAME,
    'exasol' AS TABLE_CATALOG,
    CONSTRAINT_SCHEMA AS TABLE_SCHEMA,
    CONSTRAINT_TABLE AS TABLE_NAME,
    CASE
        WHEN CONSTRAINT_TYPE = 'PRIMARY KEY' THEN 'PRIMARY KEY'
        WHEN CONSTRAINT_TYPE = 'FOREIGN KEY' THEN 'FOREIGN KEY'
        WHEN CONSTRAINT_TYPE = 'NOT NULL' THEN 'CHECK'
        ELSE CONSTRAINT_TYPE
    END AS CONSTRAINT_TYPE,
    'NO' AS IS_DEFERRABLE,
    'NO' AS INITIALLY_DEFERRED,
    CASE WHEN CONSTRAINT_ENABLED THEN 'YES' ELSE 'NO' END AS ENFORCED,
    'YES' AS NULLS_DISTINCT
FROM SYS.EXA_DBA_CONSTRAINTS;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS
SELECT
    'exasol' AS CONSTRAINT_CATALOG,
    CONSTRAINT_SCHEMA AS CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS CONSTRAINT_NAME,
    'exasol' AS TABLE_CATALOG,
    CONSTRAINT_SCHEMA AS TABLE_SCHEMA,
    CONSTRAINT_TABLE AS TABLE_NAME,
    COLUMN_NAME AS COLUMN_NAME,
    ORDINAL_POSITION AS ORDINAL_POSITION,
    ORDINAL_POSITION AS POSITION_IN_UNIQUE_CONSTRAINT
FROM SYS.EXA_DBA_CONSTRAINT_COLUMNS;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS
SELECT
    'exasol' AS CONSTRAINT_CATALOG,
    CONSTRAINT_SCHEMA AS CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS CONSTRAINT_NAME,
    'exasol' AS UNIQUE_CONSTRAINT_CATALOG,
    REFERENCED_SCHEMA AS UNIQUE_CONSTRAINT_SCHEMA,
    CONSTRAINT_NAME AS UNIQUE_CONSTRAINT_NAME,
    'NONE' AS MATCH_OPTION,
    'NO ACTION' AS UPDATE_RULE,
    'NO ACTION' AS DELETE_RULE
FROM SYS.EXA_DBA_CONSTRAINT_COLUMNS
WHERE CONSTRAINT_TYPE = 'FOREIGN KEY'
GROUP BY CONSTRAINT_SCHEMA, CONSTRAINT_NAME, REFERENCED_SCHEMA;

CREATE OR REPLACE VIEW INFORMATION_SCHEMA.TRIGGERS AS
SELECT
    CAST(NULL AS VARCHAR(128)) AS TRIGGER_CATALOG,
    CAST(NULL AS VARCHAR(128)) AS TRIGGER_SCHEMA,
    CAST(NULL AS VARCHAR(128)) AS TRIGGER_NAME,
    CAST(NULL AS VARCHAR(64)) AS EVENT_MANIPULATION,
    CAST(NULL AS VARCHAR(64)) AS ACTION_ORIENTATION,
    CAST(NULL AS VARCHAR(2000)) AS ACTION_CONDITION,
    CAST(NULL AS VARCHAR(2000000)) AS ACTION_STATEMENT,
    CAST(NULL AS VARCHAR(64)) AS ACTION_TIMING,
    CAST(NULL AS VARCHAR(128)) AS EVENT_OBJECT_CATALOG,
    CAST(NULL AS VARCHAR(128)) AS EVENT_OBJECT_SCHEMA,
    CAST(NULL AS VARCHAR(128)) AS EVENT_OBJECT_TABLE,
    CAST(NULL AS VARCHAR(128)) AS ACTION_REFERENCE_OLD_TABLE,
    CAST(NULL AS VARCHAR(128)) AS ACTION_REFERENCE_NEW_TABLE
FROM (SELECT 1 AS DUMMY)
WHERE 1 = 0;
